/**
 * The nightly token sync converts upstream themes onto the nldesign vocabulary.
 * Two of its runs did damage (#526, #982): they replaced a hand-resolved set
 * with the raw upstream dump, and dropped the local values people had added.
 * These tests pin the parts that decide what the sync may touch and what it
 * keeps.
 */
import { describe, expect, it } from 'vitest'
import {
	buildThemeCss,
	classifySet,
	kebabName,
	localOverrides,
	withOverrides,
	declarations,
	OVERRIDES_HEADING,
} from '../../scripts/sync-upstream-tokens.mjs'

describe('classifySet', () => {
	it('leaves a hand-resolved set alone even when upstream has the organisation', () => {
		const zwolle =
			'/**\n * Gemeente Zwolle — Token Set\n *\n * hand-authored the way css/tokens/cunningham.css is\n */\n:root {\n\t--nldesign-color-primary: #476db8;\n}\n'
		expect(classifySet(zwolle, true)).toBe('hand')
	})

	it('takes over a set the old raw sync wrote', () => {
		const raw =
			'/**\n * Borne Design Tokens\n *\n * Auto-generated from nl-design-system/themes repository.\n */\n:root {\n}\n'
		expect(classifySet(raw, true)).toBe('raw-sync')
	})

	it('recognises its own converted output, but not a converted set from elsewhere', () => {
		const head =
			'/* GENERATED by Thematiq TokenSetConverterService — do not edit by hand.\n * Re-run the conversion instead. */\n:root {\n'
		expect(
			classifySet(
				head
					+ '\t *    source:          nl-design-system/themes proprietary/borne-design-tokens\n}\n',
				true,
			),
		).toBe('converted')
		expect(
			classifySet(head + '\t *    source:          (pasted)\n}\n', true),
		).toBe('hand')
	})

	it('treats an unknown organisation as new, and a manifest-only set as hand authored', () => {
		expect(classifySet(null, false)).toBe('new')
		expect(classifySet(null, true)).toBe('hand')
	})
})

describe('buildThemeCss', () => {
	it('names tokens like style-dictionary name/kebab and keeps references as var()', () => {
		const css = buildThemeCss(
			{
				zwolle: { color: { blue: { 50: { value: 'hsl(220 44% 50%)' } } } },
				utrecht: {
					button: {
						backgroundColor: { value: '{zwolle.color.blue.50}' },
						boxShadow: { $value: 'inset 0 -4px {zwolle.color.blue.50}' },
					},
				},
			},
			'zwolle',
		)
		expect(css.startsWith('.zwolle-theme {\n')).toBe(true)
		expect(css).toContain('\t--zwolle-color-blue-50: hsl(220 44% 50%);')
		expect(css).toContain(
			'\t--utrecht-button-background-color: var(--zwolle-color-blue-50);',
		)
		expect(css).toContain(
			'\t--utrecht-button-box-shadow: inset 0 -4px var(--zwolle-color-blue-50);',
		)
	})

	it('drops composite values it cannot express and joins font stacks', () => {
		const css = buildThemeCss(
			{
				x: {
					typo: { value: { fontSize: '1rem' } },
					font: { value: ['Arial', 'sans-serif'] },
				},
			},
			'x',
		)
		expect(css).not.toContain('typo')
		expect(css).toContain('\t--x-font: Arial, sans-serif;')
	})

	it('splits camel humps and letter-digit runs the way lodash kebabCase does', () => {
		expect(kebabName(['utrecht', 'heading1', 'fontSize'])).toBe(
			'utrecht-heading-1-font-size',
		)
	})
})

describe('local overrides', () => {
	const old = [
		'/** Auto-generated from nl-design-system/themes repository. */',
		':root {',
		'\t--nldesign-color-primary: #4376fc;',
		'\t--noaberkracht-color-blue: #012c9d;',
		'\t--denhaag-sidenav-link-active-color: #2e5ed9;',
		'\t--nldesign-color-footer-background: #2e5ed9;',
		'}',
	].join('\n')

	it('keeps what a person added to a raw-sync set, not what upstream wrote', () => {
		const raw = new Set([
			'--nldesign-color-primary',
			'--noaberkracht-color-blue',
		])
		const kept = localOverrides(old, 'raw-sync', raw, new Map())
		expect(kept).toEqual([
			['--denhaag-sidenav-link-active-color', '#2e5ed9'],
			['--nldesign-color-footer-background', '#2e5ed9'],
		])
	})

	it('does not keep a value the new conversion declares itself', () => {
		const kept = localOverrides(
			old,
			'raw-sync',
			new Set(),
			new Map([
				['--nldesign-color-primary', '#f0b800'],
				['--noaberkracht-color-blue', '#012c9d'],
			]),
		)
		expect(kept.map(([name]) => name)).toEqual([
			'--denhaag-sidenav-link-active-color',
			'--nldesign-color-footer-background',
		])
	})

	it('writes the overrides inside :root and reads them back on the next run', () => {
		const converted =
			'/* GENERATED by Thematiq TokenSetConverterService */\n:root {\n\t--nldesign-color-primary: #f0b800;\n\n\t/* 4. Provenance */\n}\n'
		const css = withOverrides(converted, [
			['--denhaag-sidenav-link-active-color', '#2e5ed9'],
		])
		expect(
			css
				.trim()
				.endsWith('\t--denhaag-sidenav-link-active-color: #2e5ed9;\n}'),
		).toBe(true)
		expect(css).toContain(OVERRIDES_HEADING)
		expect(declarations(css).get('--nldesign-color-primary')).toBe('#f0b800')
		expect(
			localOverrides(css, 'converted', new Set(), declarations(css)),
		).toEqual([['--denhaag-sidenav-link-active-color', '#2e5ed9']])
	})

	it('adds nothing when there is nothing to keep', () => {
		const converted = ':root {\n}\n'
		expect(withOverrides(converted, [])).toBe(converted)
	})
})

describe('coverage claims', () => {
	it('rewrites the bridge line and its prose, across the comment line break', async () => {
		const { rewriteBridge } =
			await import('../../scripts/update-coverage-claims.mjs')
		const bridge = [
			' *   coverage: listed=52 roleLayer=8 nldesignOnly=41 denhaagComponents=10',
			' * Of the listed sets, 8 carry the full `--utrecht-*` role layer, 41 declare',
			' * only `--nldesign-*`, and 10 declare Den Haag component properties.',
		].join('\n')
		const out = rewriteBridge(bridge, {
			listed: 52,
			roleLayer: 10,
			nldesignOnly: 37,
			denhaagComponents: 11,
		})
		expect(out).toContain(
			'coverage: listed=52 roleLayer=10 nldesignOnly=37 denhaagComponents=11',
		)
		expect(out).toContain(
			'Of the listed sets, 10 carry the full `--utrecht-*` role layer, 37 declare',
		)
		expect(out).toContain('and 11 declare Den Haag')
	})

	it('rewrites the docs table rows', async () => {
		const { rewriteDoc } =
			await import('../../scripts/update-coverage-claims.mjs')
		const doc =
			'Measured coverage of the listed sets (`token-sets.json`, 52 sets):\n\n| the full `--utrecht-*` role layer | 8 |\n| only `--nldesign-*` | 41 |\n| Den Haag component properties | 10 |\n'
		const out = rewriteDoc(doc, {
			listed: 53,
			roleLayer: 10,
			nldesignOnly: 37,
			denhaagComponents: 10,
		})
		expect(out).toContain('(`token-sets.json`, 53 sets)')
		expect(out).toContain('| the full `--utrecht-*` role layer | 10 |')
		expect(out).toContain('| only `--nldesign-*` | 37 |')
	})
})

describe('withManifestPrimary', () => {
	it('hands the committed primary to a theme that has no primary token (buren, venray)', async () => {
		const { withManifestPrimary } =
			await import('../../scripts/sync-upstream-tokens.mjs')
		const css = withManifestPrimary(
			'.buren-theme {\n\t--buren-color-red: #d41422;\n}\n',
			{ slug: 'buren', manifestPrimary: '#D41422' },
		)
		expect(css).toContain('\t--buren-color-primary: #d41422;\n}')
	})

	it('never overrides a primary the theme declares', async () => {
		const { withManifestPrimary } =
			await import('../../scripts/sync-upstream-tokens.mjs')
		const own =
			'.x-theme {\n\t--utrecht-button-primary-action-background-color: #111111;\n}\n'
		expect(
			withManifestPrimary(own, { slug: 'x', manifestPrimary: '#222222' }),
		).toBe(own)
		expect(
			withManifestPrimary('.x-theme {\n}\n', {
				slug: 'x',
				manifestPrimary: null,
			}),
		).toBe('.x-theme {\n}\n')
	})
})
