<?php

/**
 * The shipped contrast verdicts as a machine-readable document.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V. <info@conduction.nl>
 *
 * `scripts/audit-token-sets.mjs` folds each set's contrast verdict into the
 * per-set coverage table it prints. Reimplementing WCAG relative luminance,
 * colour parsing and `color-mix()` in a second language to do that would be two
 * engines that can disagree about whether a set passes, which is the kind of
 * disagreement nobody notices until a published claim is wrong.
 *
 * So one engine writes two files from one `composer docs:contrast-report` run:
 * the markdown report a person reads, and this JSON the Node audit reads. This
 * renderer is a class of its own rather than a second method on
 * `ShippedTokenSetAuditService` because that class measures; rendering is a
 * separate job, and it was already at its complexity ceiling.
 *
 * @category Service
 * @package  OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/specs/token-set-contrast-audit/spec.md#requirement-reproducible-contrast-report
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

/**
 * Renders the contrast audit's verdicts as deterministic JSON.
 *
 * @spec openspec/specs/token-set-contrast-audit/spec.md#requirement-reproducible-contrast-report
 */
class ContrastVerdictDocument {

	/**
	 * The header comment the generated file carries, so a reader who opens it
	 * knows it is not hand-maintained.
	 */
	public const HEADER = 'GENERATED by ContrastVerdictDocument::render()'
		. ' — do not edit by hand. Regenerate with: composer docs:contrast-report';

	/**
	 * Render the verdicts of every audited set.
	 *
	 * Deterministic: the rows come from `ShippedTokenSetAuditService::auditAll()`,
	 * which orders by id, and nothing else here depends on ordering.
	 *
	 * @param array<int, array<string, mixed>> $rows The audit rows.
	 *
	 * @return string The pretty-printed JSON document, newline-terminated.
	 *
	 * @spec openspec/specs/token-set-contrast-audit/spec.md#requirement-reproducible-contrast-report
	 */
	public function render(array $rows): string {
		$sets = [];
		foreach ($rows as $row) {
			$sets[(string)$row['id']] = [
				'verdict' => $row['verdict'],
				'textRatio' => $row['textRatio'],
				'uiRatio' => $row['uiRatio'],
				'textThreshold' => $row['textThreshold'],
				'uiThreshold' => $row['uiThreshold'],
			];
		}

		return json_encode(
			// `pairs` names what each ratio compared, read straight off the
			// service that compares them. Without it the column names carry the
			// whole explanation, and "textRatio" reads as body ink when it is
			// the primary colour against the colour written on it. The Node
			// audit takes `parsed.sets`, so this key costs it nothing.
			//
			// (object) so an empty audit renders `"sets": {}` and not `"sets": []`.
			// PHP encodes an empty array as a JSON list, and the Node audit
			// indexes this by set id, so a list would make an empty catalogue
			// fail differently from a full one for no reason.
			[
				'$comment' => self::HEADER,
				'pairs' => [
					'textRatio' => ShippedTokenSetAuditService::TEXT_PAIR,
					'uiRatio' => ShippedTokenSetAuditService::UI_PAIR,
				],
				'sets' => (object)$sets,
			],
			// PRESERVE_ZERO_FRACTION keeps a threshold of 3.0 as `3.0` rather
			// than `3`. The file is compared byte for byte by its staleness
			// check, so a value whose type depends on whether it happens to be
			// whole is a diff waiting to happen.
			(JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION)
		) . "\n";
	}//end render()
}//end class
