<?php

/**
 * NL Design Custom Overrides Service.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCA\Thematiq\AppInfo\Application;
use OCP\App\IAppManager;
use OCP\IConfig;
use RuntimeException;

/**
 * Service for reading and writing the custom-overrides.css file.
 *
 * This service is the sole write path for user-defined token customizations.
 * It validates all token names against the TokenRegistry before writing.
 *
 * The CSS file format is strictly controlled:
 * - One :root {} block with the light values, read back by read()
 * - For every brand-layer colour override, the two dark scopes of the generated dark
 *   stylesheets with its derived dark value, so a user who chose the dark
 *   theme (whose colours Nextcloud declares on body) and a user whose system
 *   is dark see the same colour
 * - One declaration per line
 * - Each declaration carries !important so user overrides win the cascade over
 *   the nldesign design-system stylesheets and Nextcloud core theming
 * - No selectors other than :root and the two dark scopes
 *
 * A SET ON NO DESIGN SYSTEM NEVER READS THE SHARED FILE.
 *
 * `css/custom-overrides.css` holds the edits made on every set that wears a
 * design system. A set on `none` — the stock `nextcloud` set, and every
 * theme saved off it — keeps its edits in a file of its own,
 * `css/custom-overrides-{set}.css`, and only that file is loaded while it is
 * the set on the page. Such a set is Nextcloud plus its own values and
 * nothing else: the stock set loads no token file at all, so emptying its
 * edit file — the reset — gives stock back.
 *
 * Before the split there was one file, loaded whatever the set. A value an
 * admin pinned while on some other theme stayed on the page after switching
 * back to "Nextcloud", so the stock set was not stock, and every theme saved
 * off it wore the other themes' pinned values too.
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */
class CustomOverridesService {

	/**
	 * The scope of a user whose system is dark and who chose no theme (as in
	 * the generated dark stylesheets).
	 *
	 * @var string
	 */
	private const SYSTEM_DARK_SELECTOR = 'body:not([data-theme-light]):not([data-theme-dark])'
		. ':not([data-theme-light-highcontrast]):not([data-theme-dark-highcontrast])';

	/**
	 * The scope of a user who chose the dark theme (as in the generated dark stylesheets).
	 *
	 * @var string
	 */
	private const CHOSEN_DARK_SELECTOR = 'body[data-theme-dark],' . PHP_EOL . 'body[data-themes*=dark]';

	/**
	 * The CSS file header comment.
	 *
	 * @var string
	 */
	private const CSS_HEADER = '/* NL Design — custom token overrides. Generated by theme editor. Do not edit manually. */';

	/**
	 * The overrides file of every set that wears a design system (under `css/`, no extension).
	 *
	 * @var string
	 */
	public const FILE = 'custom-overrides';

	/**
	 * The app manager for resolving the CSS file path.
	 *
	 * @var IAppManager
	 */
	private IAppManager $appManager;

	/**
	 * The CSS parser service (shared :root-block parsing, avoids duplication).
	 *
	 * @var CssParserService
	 */
	private CssParserService $cssParser;

	/**
	 * The dark palette, which derives a colour override's dark value exactly
	 * as the generated dark stylesheets do.
	 *
	 * @var DarkPaletteService
	 */
	private DarkPaletteService $darkPalette;

	/**
	 * The app config, for the active set when a caller names none.
	 *
	 * @var IConfig|null
	 */
	private ?IConfig $config;

	/**
	 * Which design system a set wears, for choosing its file.
	 *
	 * @var DesignSystemService|null
	 */
	private ?DesignSystemService $designSystems;

	/**
	 * Constructor.
	 *
	 * @param IAppManager $appManager The app manager.
	 * @param CssParserService $cssParser CSS parser for :root block extraction.
	 * @param DarkPaletteService $darkPalette Derives each colour override's dark value.
	 * @param IConfig|null $config The app config. With the next one, what picks a set's own file;
	 *                             without them every set reads the shared file.
	 * @param DesignSystemService|null $designSystems The token set metadata.
	 */
	public function __construct(
		IAppManager $appManager,
		CssParserService $cssParser,
		DarkPaletteService $darkPalette,
		?IConfig $config = null,
		?DesignSystemService $designSystems = null,
	) {
		$this->appManager = $appManager;
		$this->cssParser = $cssParser;
		$this->darkPalette = $darkPalette;
		$this->config = $config;
		$this->designSystems = $designSystems;
	}//end __construct()

	/**
	 * The overrides file a token set reads, under `css/` and without extension.
	 *
	 * @param string $tokenSet       The token set id.
	 * @param string $designSystemId The design system the set wears.
	 *
	 * @return string `custom-overrides-{set}` for a set on `none`, {@see self::FILE} for every other.
	 *
	 * @spec openspec/specs/css-architecture/spec.md
	 */
	public static function fileFor(string $tokenSet, string $designSystemId): string {
		// The stock set is on `none` by definition; named here too so its
		// file does not depend on its metadata being readable.
		if ($designSystemId !== 'none' && $tokenSet !== CssInjectionService::STOCK_TOKEN_SET) {
			return self::FILE;
		}

		return self::FILE . '-' . preg_replace('/[^a-z0-9-]/', '', strtolower($tokenSet));
	}//end fileFor()

	/**
	 * Get the absolute path to the overrides file of a token set.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return string The CSS file path.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - fileFor() is static so CssInjectionService can ask without an instance
	 */
	private function getFilePath(?string $tokenSet): string {
		// Built without the set lookup (a caller that constructs the service
		// by hand): the shared file, which is every set's on a design system.
		if ($this->config === null || $this->designSystems === null) {
			return $this->appManager->getAppPath('thematiq') . '/css/' . self::FILE . '.css';
		}

		if ($tokenSet === null) {
			$tokenSet = $this->config->getAppValue(
				Application::APP_ID,
				'token_set',
				CssInjectionService::STOCK_TOKEN_SET
			);
		}

		$meta = $this->designSystems->getTokenSetMeta(tokenSetId: $tokenSet);
		$file = self::fileFor(tokenSet: $tokenSet, designSystemId: (string)($meta['design_system'] ?? 'nldesign'));

		return $this->appManager->getAppPath('thematiq') . '/css/' . $file . '.css';
	}//end getFilePath()

	/**
	 * Ensure the overrides file of a token set exists.
	 *
	 * Creates an empty :root {} file if the file is absent.
	 * Safe to call on every page load (no-op if file already exists).
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return void
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
	 */
	public function ensureExists(?string $tokenSet = null): void {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			$this->writeFile(tokens: [], path: $path);
		}

	}//end ensureExists()

	/**
	 * Read the current custom overrides from the CSS file.
	 *
	 * Returns only the tokens explicitly set in the file.
	 * Does not return defaults or resolved values from the full CSS stack.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return array<string, string> Map of token name => value for all overrides in the file.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 */
	public function read(?string $tokenSet = null): array {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			return [];
		}

		$content = file_get_contents($path);
		if ($content === false) {
			return [];
		}

		return $this->parseDeclarations(css: $content);
	}//end read()

	/**
	 * Write a new set of token overrides to the overrides file of a token set.
	 *
	 * Only tokens present in TokenRegistry are accepted — others are silently ignored.
	 * Writes atomically via a temp file + rename to avoid partial writes.
	 *
	 * @param array<string, string> $tokens   Map of token name => value to persist.
	 * @param string|null           $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the file cannot be written.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
	 */
	public function write(array $tokens, ?string $tokenSet = null): void {
		$validated = $this->filterEditable(tokens: $tokens);

		$this->writeFile(tokens: $validated, path: $this->getFilePath(tokenSet: $tokenSet));

	}//end write()

	/**
	 * List the tokens in a map that write() would not persist, with the reason.
	 *
	 * A token is refused when its name is not in the TokenRegistry, when its value
	 * is not a string, or when its value carries a character the writer strips to
	 * keep the file a single :root block. Callers that answer an admin use this to
	 * refuse the whole save instead of reporting tokens that never reached the file.
	 *
	 * @param array<array-key, mixed> $tokens Input token map.
	 *
	 * @return array<string, string> Map of refused token name => reason; empty when all are accepted.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/authoring-token-value-types/tasks.md#task-2.1
	 */
	public function findRejected(array $tokens): array {
		$rejected = [];
		foreach ($tokens as $name => $value) {
			$name = (string)$name;
			if (TokenRegistry::isEditable(tokenName: $name) === false) {
				$rejected[$name] = 'not an editable token';
				continue;
			}

			if (is_string($value) === false || $this->isUnsafeValue(value: $value) === true) {
				$rejected[$name] = 'not an allowed value';
			}
		}

		return $rejected;
	}//end findRejected()

	/**
	 * Tell whether a value carries a character that would break out of the :root block.
	 *
	 * @param string $value The token value.
	 *
	 * @return bool True when the writer would drop the value.
	 */
	private function isUnsafeValue(string $value): bool {
		return preg_match('/[{};]|\/\*|\*\//', $value) === 1;
	}//end isUnsafeValue()

	/**
	 * Filter a token map to only those present in the registry.
	 *
	 * @param array<string, string> $tokens Input token map.
	 *
	 * @return array<string, string> Filtered tokens.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
	 */
	private function filterEditable(array $tokens): array {
		$result = [];
		foreach ($tokens as $name => $value) {
			if (TokenRegistry::isEditable(tokenName: $name) === true) {
				$result[$name] = $value;
			}
		}

		return $result;
	}//end filterEditable()

	/**
	 * Write the CSS file atomically using a temp file + rename.
	 *
	 * @param array<string, string> $tokens Validated token map to write.
	 * @param string                $path   The file to write.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the temp file cannot be written or renamed.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
	 */
	private function writeFile(array $tokens, string $path): void {
		$tmpPath = $path . '.tmp';

		$css = $this->buildCss(tokens: $tokens);

		$result = file_put_contents(filename: $tmpPath, data: $css);
		if ($result === false) {
			throw new RuntimeException(
				message: 'Could not write ' . $tmpPath . '. Ensure the web server has write access to the css/ directory.'
			);
		}

		if (rename(from: $tmpPath, to: $path) === false) {
			if (file_exists(filename: $tmpPath) === true) {
				unlink(filename: $tmpPath);
			}

			throw new RuntimeException(
				message: 'Temp file could not be renamed to ' . $path . '.'
			);
		}

	}//end writeFile()

	/**
	 * Build the CSS file content from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return string The CSS file content.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
	 */
	private function buildCss(array $tokens): string {
		$header = self::CSS_HEADER . PHP_EOL;

		if (empty($tokens) === true) {
			return $header . ':root {}' . PHP_EOL;
		}

		$lines = $this->buildDeclarationLines(tokens: $tokens);
		$css = $header . ':root {' . PHP_EOL . implode(PHP_EOL, $lines) . PHP_EOL . '}' . PHP_EOL;

		$darkLines = $this->buildDeclarationLines(tokens: $this->darkValues(tokens: $tokens));
		if (empty($darkLines) === true) {
			return $css;
		}

		// The same two scopes the generated dark stylesheets use. A user who
		// chose the dark theme gets Nextcloud's dark colours declared on body,
		// which a :root value never reaches; a body-level declaration wins for
		// both kinds of dark user.
		$css .= '@media (prefers-color-scheme: dark) {' . PHP_EOL
			. '	' . self::SYSTEM_DARK_SELECTOR . ' {' . PHP_EOL
			. '	' . implode(PHP_EOL . '	', $darkLines) . PHP_EOL
			. '	}' . PHP_EOL
			. '}' . PHP_EOL
			. self::CHOSEN_DARK_SELECTOR . ' {' . PHP_EOL
			. implode(PHP_EOL, $darkLines) . PHP_EOL
			. '}' . PHP_EOL;

		return $css;
	}//end buildCss()

	/**
	 * The dark value of every brand-layer colour override: derived as the
	 * generated dark stylesheets derive it, or the light value when it is not
	 * a colour literal, so both kinds of dark user still see the same thing.
	 *
	 * Only the brand layer (Nextcloud's own variables) is split today, because
	 * only those does Nextcloud re-declare on body for a chosen theme. Component
	 * tokens are left out: both kinds of dark user already get the same body
	 * value from the generated dark stylesheet, and a body-level copy here would
	 * outrank the primary-lock layer, which locks them at :root.
	 *
	 * @param array<string, string> $tokens Token name => light value.
	 *
	 * @return array<string, string> Colour token name => dark value.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/authoring-token-value-types/tasks.md#task-2.2
	 * @spec openspec/changes/theme-vocabulary-complete/tasks.md#task-1.5
	 */
	private function darkValues(array $tokens): array {
		$registry = TokenRegistry::getTokens();
		$dark = [];
		foreach ($tokens as $name => $value) {
			if (($registry[$name]['type'] ?? '') !== 'color' || ($registry[$name]['group'] ?? '') !== 'brand') {
				continue;
			}

			// A settable theme variable gets no derived dark value: Nextcloud
			// calculates its own per theme, and the zero-specificity dark reset
			// in theme-scopes.css leaves that value in place unless a dark one is
			// given on purpose (theme-vocabulary-complete).
			if (TokenRegistry::settableToken(name: $name) !== null) {
				continue;
			}

			$dark[$name] = ($this->darkPalette->deriveDarkValue(token: $name, lightValue: $value, context: $tokens) ?? $value);
		}

		return $dark;
	}//end darkValues()

	/**
	 * Build individual CSS declaration lines from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return array<string> List of CSS declaration lines.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
	 * @spec openspec/changes/theme-vocabulary-complete/tasks.md#task-1.5
	 */
	private function buildDeclarationLines(array $tokens): array {
		$lines = [];
		foreach ($tokens as $name => $value) {
			// Reject any value containing CSS injection characters.
			if ($this->isUnsafeValue(value: $value) === true) {
				continue;
			}

			$safeValue = str_replace(["\n", "\r", ';', '{', '}', '/*', '*/'], '', $value);
			// A settable theme variable is stored as its `--nldesign-*` token:
			// theme-scopes.css redeclares the Nextcloud variable on every child
			// of body from that token, so a `:root` value under the Nextcloud
			// name would be shadowed and do nothing.
			$safeName = preg_replace('/[^a-zA-Z0-9\-]/', '', (TokenRegistry::settableToken(name: $name) ?? $name));

			// Strip any pre-existing !important the caller may have included; it is
			// re-applied uniformly below so the round-trip stays canonical.
			$safeValue = trim(preg_replace('/\s*!\s*important\s*$/i', '', $safeValue));

			// Emit each user override with !important so it wins the cascade.
			// The nldesign design-system stylesheets (theme/overrides/element-overrides.css)
			// re-declare every editable token with !important, and Nextcloud core theming
			// also overrides tokens like --color-primary. custom-overrides.css loads last,
			// but without !important it loses the cascade and the saved theme has no visible
			// effect. !important here is scoped to user-set overrides only (this file only
			// ever contains tokens the admin explicitly set in the editor), so it does not
			// blanket-!important the full token registry.
			$lines[] = '  ' . $safeName . ': ' . $safeValue . ' !important;';
		}//end foreach

		return $lines;
	}//end buildDeclarationLines()

	/**
	 * Parse CSS custom property declarations from a :root {} block.
	 *
	 * Delegates to CssParserService to avoid duplicating the parse logic.
	 *
	 * @param string $css The raw CSS string.
	 *
	 * @return array<string, string> Map of token name => value.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 * @spec openspec/changes/theme-vocabulary-complete/tasks.md#task-1.5
	 */
	private function parseDeclarations(string $css): array {
		$declarations = [];
		foreach ($this->cssParser->parseRootBlock(css: $css) as $name => $value) {
			// Read a stored settable token back under the Nextcloud name the
			// editor and the registry use.
			$declarations[(TokenRegistry::settableName(token: $name) ?? $name)] = $value;
		}

		return $declarations;
	}//end parseDeclarations()

	/**
	 * Return the raw CSS file content for download.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return string The raw file content, or an empty :root {} if the file does not exist.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
	 */
	public function getRawContent(?string $tokenSet = null): string {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			return self::CSS_HEADER . PHP_EOL . ':root {}' . PHP_EOL;
		}

		$content = file_get_contents(filename: $path);
		if ($content === false) {
			return '';
		}

		return $content;
	}//end getRawContent()
}//end class
