<?php

/**
 * NL Design Custom Overrides Service.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCA\Thematiq\AppInfo\Application;
use OCP\App\IAppManager;
use OCP\IConfig;
use RuntimeException;

/**
 * Service for reading and writing the custom-overrides.css file.
 *
 * This service is the sole write path for user-defined token customizations.
 * It validates all token names against the TokenRegistry before writing.
 *
 * The CSS file format is strictly controlled:
 * - Single :root {} block
 * - One declaration per line
 * - Each declaration carries !important so user overrides win the cascade over
 *   the nldesign design-system stylesheets and Nextcloud core theming
 * - No selectors other than :root
 *
 * A SET ON NO DESIGN SYSTEM NEVER READS THE SHARED FILE.
 *
 * `css/custom-overrides.css` holds the edits made on every set that wears a
 * design system. A set on `none` — the stock `nextcloud` set, and every
 * theme saved off it — keeps its edits in a file of its own,
 * `css/custom-overrides-{set}.css`, and only that file is loaded while it is
 * the set on the page. Such a set is Nextcloud plus its own values and
 * nothing else: the stock set loads no token file at all, so emptying its
 * edit file — the reset — gives stock back.
 *
 * Before the split there was one file, loaded whatever the set. A value an
 * admin pinned while on some other theme stayed on the page after switching
 * back to "Nextcloud", so the stock set was not stock, and every theme saved
 * off it wore the other themes' pinned values too.
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */
class CustomOverridesService {

	/**
	 * The CSS file header comment.
	 *
	 * @var string
	 */
	private const CSS_HEADER = '/* NL Design — custom token overrides. Generated by theme editor. Do not edit manually. */';

	/**
	 * The overrides file of every set that wears a design system (under `css/`, no extension).
	 *
	 * @var string
	 */
	public const FILE = 'custom-overrides';

	/**
	 * The app manager for resolving the CSS file path.
	 *
	 * @var IAppManager
	 */
	private IAppManager $appManager;

	/**
	 * The CSS parser service (shared :root-block parsing, avoids duplication).
	 *
	 * @var CssParserService
	 */
	private CssParserService $cssParser;

	/**
	 * The app config, for the active set when a caller names none.
	 *
	 * @var IConfig
	 */
	private IConfig $config;

	/**
	 * Which design system a set wears, for choosing its file.
	 *
	 * @var DesignSystemService
	 */
	private DesignSystemService $designSystems;

	/**
	 * Constructor.
	 *
	 * @param IAppManager $appManager The app manager.
	 * @param CssParserService $cssParser CSS parser for :root block extraction.
	 * @param IConfig $config The app config.
	 * @param DesignSystemService $designSystems The token set metadata.
	 */
	public function __construct(
		IAppManager $appManager,
		CssParserService $cssParser,
		IConfig $config,
		DesignSystemService $designSystems,
	) {
		$this->appManager = $appManager;
		$this->cssParser = $cssParser;
		$this->config = $config;
		$this->designSystems = $designSystems;
	}//end __construct()

	/**
	 * The overrides file a token set reads, under `css/` and without extension.
	 *
	 * @param string $tokenSet       The token set id.
	 * @param string $designSystemId The design system the set wears.
	 *
	 * @return string `custom-overrides-{set}` for a set on `none`, {@see self::FILE} for every other.
	 *
	 * @spec openspec/specs/css-architecture/spec.md
	 */
	public static function fileFor(string $tokenSet, string $designSystemId): string {
		// The stock set is on `none` by definition; named here too so its
		// file does not depend on its metadata being readable.
		if ($designSystemId !== 'none' && $tokenSet !== CssInjectionService::STOCK_TOKEN_SET) {
			return self::FILE;
		}

		return self::FILE . '-' . preg_replace('/[^a-z0-9-]/', '', strtolower($tokenSet));
	}//end fileFor()

	/**
	 * Get the absolute path to the overrides file of a token set.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return string The CSS file path.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - fileFor() is static so CssInjectionService can ask without an instance
	 */
	private function getFilePath(?string $tokenSet): string {
		if ($tokenSet === null) {
			$tokenSet = $this->config->getAppValue(
				Application::APP_ID,
				'token_set',
				CssInjectionService::STOCK_TOKEN_SET
			);
		}

		$meta = $this->designSystems->getTokenSetMeta(tokenSetId: $tokenSet);
		$file = self::fileFor(tokenSet: $tokenSet, designSystemId: (string)($meta['design_system'] ?? 'nldesign'));

		return $this->appManager->getAppPath('thematiq') . '/css/' . $file . '.css';
	}//end getFilePath()

	/**
	 * Ensure the overrides file of a token set exists.
	 *
	 * Creates an empty :root {} file if the file is absent.
	 * Safe to call on every page load (no-op if file already exists).
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return void
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
	 */
	public function ensureExists(?string $tokenSet = null): void {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			$this->writeFile(tokens: [], path: $path);
		}

	}//end ensureExists()

	/**
	 * Read the current custom overrides from the CSS file.
	 *
	 * Returns only the tokens explicitly set in the file.
	 * Does not return defaults or resolved values from the full CSS stack.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return array<string, string> Map of token name => value for all overrides in the file.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 */
	public function read(?string $tokenSet = null): array {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			return [];
		}

		$content = file_get_contents($path);
		if ($content === false) {
			return [];
		}

		return $this->parseDeclarations(css: $content);
	}//end read()

	/**
	 * Write a new set of token overrides to the overrides file of a token set.
	 *
	 * Only tokens present in TokenRegistry are accepted — others are silently ignored.
	 * Writes atomically via a temp file + rename to avoid partial writes.
	 *
	 * @param array<string, string> $tokens   Map of token name => value to persist.
	 * @param string|null           $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the file cannot be written.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
	 */
	public function write(array $tokens, ?string $tokenSet = null): void {
		$validated = $this->filterEditable(tokens: $tokens);

		$this->writeFile(tokens: $validated, path: $this->getFilePath(tokenSet: $tokenSet));

	}//end write()

	/**
	 * Filter a token map to only those present in the registry.
	 *
	 * @param array<string, string> $tokens Input token map.
	 *
	 * @return array<string, string> Filtered tokens.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
	 */
	private function filterEditable(array $tokens): array {
		$result = [];
		foreach ($tokens as $name => $value) {
			if (TokenRegistry::isEditable(tokenName: $name) === true) {
				$result[$name] = $value;
			}
		}

		return $result;
	}//end filterEditable()

	/**
	 * Write the CSS file atomically using a temp file + rename.
	 *
	 * @param array<string, string> $tokens Validated token map to write.
	 * @param string                $path   The file to write.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the temp file cannot be written or renamed.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
	 */
	private function writeFile(array $tokens, string $path): void {
		$tmpPath = $path . '.tmp';

		$css = $this->buildCss(tokens: $tokens);

		$result = file_put_contents(filename: $tmpPath, data: $css);
		if ($result === false) {
			throw new RuntimeException(
				message: 'Could not write ' . $tmpPath . '. Ensure the web server has write access to the css/ directory.'
			);
		}

		if (rename(from: $tmpPath, to: $path) === false) {
			if (file_exists(filename: $tmpPath) === true) {
				unlink(filename: $tmpPath);
			}

			throw new RuntimeException(
				message: 'Temp file could not be renamed to ' . $path . '.'
			);
		}

	}//end writeFile()

	/**
	 * Build the CSS file content from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return string The CSS file content.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
	 */
	private function buildCss(array $tokens): string {
		$header = self::CSS_HEADER . PHP_EOL;

		if (empty($tokens) === true) {
			return $header . ':root {}' . PHP_EOL;
		}

		$lines = $this->buildDeclarationLines(tokens: $tokens);

		return $header . ':root {' . PHP_EOL . implode(PHP_EOL, $lines) . PHP_EOL . '}' . PHP_EOL;
	}//end buildCss()

	/**
	 * Build individual CSS declaration lines from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return array<string> List of CSS declaration lines.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
	 */
	private function buildDeclarationLines(array $tokens): array {
		$lines = [];
		foreach ($tokens as $name => $value) {
			// Reject any value containing CSS injection characters.
			if (preg_match('/[{};]|\/\*|\*\//', $value) === 1) {
				continue;
			}

			$safeValue = str_replace(["\n", "\r", ';', '{', '}', '/*', '*/'], '', $value);
			$safeName = preg_replace('/[^a-zA-Z0-9\-]/', '', $name);

			// Strip any pre-existing !important the caller may have included; it is
			// re-applied uniformly below so the round-trip stays canonical.
			$safeValue = trim(preg_replace('/\s*!\s*important\s*$/i', '', $safeValue));

			// Emit each user override with !important so it wins the cascade.
			// The nldesign design-system stylesheets (theme/overrides/element-overrides.css)
			// re-declare every editable token with !important, and Nextcloud core theming
			// also overrides tokens like --color-primary. custom-overrides.css loads last,
			// but without !important it loses the cascade and the saved theme has no visible
			// effect. !important here is scoped to user-set overrides only (this file only
			// ever contains tokens the admin explicitly set in the editor), so it does not
			// blanket-!important the full token registry.
			$lines[] = '  ' . $safeName . ': ' . $safeValue . ' !important;';
		}//end foreach

		return $lines;
	}//end buildDeclarationLines()

	/**
	 * Parse CSS custom property declarations from a :root {} block.
	 *
	 * Delegates to CssParserService to avoid duplicating the parse logic.
	 *
	 * @param string $css The raw CSS string.
	 *
	 * @return array<string, string> Map of token name => value.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 */
	private function parseDeclarations(string $css): array {
		return $this->cssParser->parseRootBlock(css: $css);
	}//end parseDeclarations()

	/**
	 * Return the raw CSS file content for download.
	 *
	 * @param string|null $tokenSet The token set id, or null for the instance's active set.
	 *
	 * @return string The raw file content, or an empty :root {} if the file does not exist.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
	 */
	public function getRawContent(?string $tokenSet = null): string {
		$path = $this->getFilePath(tokenSet: $tokenSet);
		if (file_exists($path) === false) {
			return self::CSS_HEADER . PHP_EOL . ':root {}' . PHP_EOL;
		}

		$content = file_get_contents(filename: $path);
		if ($content === false) {
			return '';
		}

		return $content;
	}//end getRawContent()
}//end class
