<?php

/**
 * NL Design Custom Overrides Service.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCP\App\IAppManager;
use RuntimeException;

/**
 * Service for reading and writing the custom-overrides.css file.
 *
 * This service is the sole write path for user-defined token customizations.
 * It validates all token names against the TokenRegistry before writing.
 *
 * The CSS file format is strictly controlled:
 * - Single :root {} block
 * - One declaration per line
 * - Each declaration carries !important so user overrides win the cascade over
 *   the nldesign design-system stylesheets and Nextcloud core theming
 * - No selectors other than :root
 *
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
 */
class CustomOverridesService {

	/**
	 * The CSS file header comment.
	 *
	 * @var string
	 */
	private const CSS_HEADER = '/* NL Design — custom token overrides. Generated by theme editor. Do not edit manually. */';

	/**
	 * The app manager for resolving the CSS file path.
	 *
	 * @var IAppManager
	 */
	private IAppManager $appManager;

	/**
	 * The CSS parser service (shared :root-block parsing, avoids duplication).
	 *
	 * @var CssParserService
	 */
	private CssParserService $cssParser;

	/**
	 * Constructor.
	 *
	 * @param IAppManager $appManager The app manager.
	 * @param CssParserService $cssParser CSS parser for :root block extraction.
	 */
	public function __construct(IAppManager $appManager, CssParserService $cssParser) {
		$this->appManager = $appManager;
		$this->cssParser = $cssParser;
	}//end __construct()

	/**
	 * Get the absolute path to custom-overrides.css.
	 *
	 * @return string The CSS file path.
	 */
	private function getFilePath(): string {
		return $this->appManager->getAppPath('thematiq') . '/css/custom-overrides.css';
	}//end getFilePath()

	/**
	 * Ensure the custom-overrides.css file exists.
	 *
	 * Creates an empty :root {} file if the file is absent.
	 * Safe to call on every page load (no-op if file already exists).
	 *
	 * @return void
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-28
	 */
	public function ensureExists(): void {
		$path = $this->getFilePath();
		if (file_exists($path) === false) {
			$this->writeFile(tokens: []);
		}

	}//end ensureExists()

	/**
	 * Read the current custom overrides from the CSS file.
	 *
	 * Returns only the tokens explicitly set in the file.
	 * Does not return defaults or resolved values from the full CSS stack.
	 *
	 * @return array<string, string> Map of token name => value for all overrides in the file.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 */
	public function read(): array {
		$path = $this->getFilePath();
		if (file_exists($path) === false) {
			return [];
		}

		$content = file_get_contents($path);
		if ($content === false) {
			return [];
		}

		return $this->parseDeclarations(css: $content);
	}//end read()

	/**
	 * Write a new set of token overrides to custom-overrides.css.
	 *
	 * Only tokens present in TokenRegistry are accepted — others are silently ignored.
	 * Writes atomically via a temp file + rename to avoid partial writes.
	 *
	 * @param array<string, string> $tokens Map of token name => value to persist.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the file cannot be written.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-30
	 */
	public function write(array $tokens): void {
		$validated = $this->filterEditable(tokens: $tokens);

		$this->writeFile(tokens: $validated);

	}//end write()

	/**
	 * List the tokens in a map that write() would not persist, with the reason.
	 *
	 * A token is refused when its name is not in the TokenRegistry, when its value
	 * is not a string, or when its value carries a character the writer strips to
	 * keep the file a single :root block. Callers that answer an admin use this to
	 * refuse the whole save instead of reporting tokens that never reached the file.
	 *
	 * @param array<array-key, mixed> $tokens Input token map.
	 *
	 * @return array<string, string> Map of refused token name => reason; empty when all are accepted.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/authoring-token-value-types/tasks.md#task-2.1
	 */
	public function findRejected(array $tokens): array {
		$rejected = [];
		foreach ($tokens as $name => $value) {
			$name = (string)$name;
			if (TokenRegistry::isEditable(tokenName: $name) === false) {
				$rejected[$name] = 'not an editable token';
				continue;
			}

			if (is_string($value) === false || $this->isUnsafeValue(value: $value) === true) {
				$rejected[$name] = 'not an allowed value';
			}
		}

		return $rejected;
	}//end findRejected()

	/**
	 * Tell whether a value carries a character that would break out of the :root block.
	 *
	 * @param string $value The token value.
	 *
	 * @return bool True when the writer would drop the value.
	 */
	private function isUnsafeValue(string $value): bool {
		return preg_match('/[{};]|\/\*|\*\//', $value) === 1;
	}//end isUnsafeValue()

	/**
	 * Filter a token map to only those present in the registry.
	 *
	 * @param array<string, string> $tokens Input token map.
	 *
	 * @return array<string, string> Filtered tokens.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-8
	 */
	private function filterEditable(array $tokens): array {
		$result = [];
		foreach ($tokens as $name => $value) {
			if (TokenRegistry::isEditable(tokenName: $name) === true) {
				$result[$name] = $value;
			}
		}

		return $result;
	}//end filterEditable()

	/**
	 * Write the CSS file atomically using a temp file + rename.
	 *
	 * @param array<string, string> $tokens Validated token map to write.
	 *
	 * @return void
	 *
	 * @throws RuntimeException When the temp file cannot be written or renamed.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-31
	 */
	private function writeFile(array $tokens): void {
		$path = $this->getFilePath();
		$tmpPath = $path . '.tmp';

		$css = $this->buildCss(tokens: $tokens);

		$result = file_put_contents(filename: $tmpPath, data: $css);
		if ($result === false) {
			throw new RuntimeException(
				message: 'Could not write ' . $tmpPath . '. Ensure the web server has write access to the css/ directory.'
			);
		}

		if (rename(from: $tmpPath, to: $path) === false) {
			if (file_exists(filename: $tmpPath) === true) {
				unlink(filename: $tmpPath);
			}

			throw new RuntimeException(
				message: 'Temp file could not be renamed to ' . $path . '.'
			);
		}

	}//end writeFile()

	/**
	 * Build the CSS file content from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return string The CSS file content.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
	 */
	private function buildCss(array $tokens): string {
		$header = self::CSS_HEADER . PHP_EOL;

		if (empty($tokens) === true) {
			return $header . ':root {}' . PHP_EOL;
		}

		$lines = $this->buildDeclarationLines(tokens: $tokens);

		return $header . ':root {' . PHP_EOL . implode(PHP_EOL, $lines) . PHP_EOL . '}' . PHP_EOL;
	}//end buildCss()

	/**
	 * Build individual CSS declaration lines from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 *
	 * @return array<string> List of CSS declaration lines.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
	 */
	private function buildDeclarationLines(array $tokens): array {
		$lines = [];
		foreach ($tokens as $name => $value) {
			// Reject any value containing CSS injection characters.
			if ($this->isUnsafeValue(value: $value) === true) {
				continue;
			}

			$safeValue = str_replace(["\n", "\r", ';', '{', '}', '/*', '*/'], '', $value);
			$safeName = preg_replace('/[^a-zA-Z0-9\-]/', '', $name);

			// Strip any pre-existing !important the caller may have included; it is
			// re-applied uniformly below so the round-trip stays canonical.
			$safeValue = trim(preg_replace('/\s*!\s*important\s*$/i', '', $safeValue));

			// Emit each user override with !important so it wins the cascade.
			// The nldesign design-system stylesheets (theme/overrides/element-overrides.css)
			// re-declare every editable token with !important, and Nextcloud core theming
			// also overrides tokens like --color-primary. custom-overrides.css loads last,
			// but without !important it loses the cascade and the saved theme has no visible
			// effect. !important here is scoped to user-set overrides only (this file only
			// ever contains tokens the admin explicitly set in the editor), so it does not
			// blanket-!important the full token registry.
			$lines[] = '  ' . $safeName . ': ' . $safeValue . ' !important;';
		}//end foreach

		return $lines;
	}//end buildDeclarationLines()

	/**
	 * Parse CSS custom property declarations from a :root {} block.
	 *
	 * Delegates to CssParserService to avoid duplicating the parse logic.
	 *
	 * @param string $css The raw CSS string.
	 *
	 * @return array<string, string> Map of token name => value.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-29
	 */
	private function parseDeclarations(string $css): array {
		return $this->cssParser->parseRootBlock(css: $css);
	}//end parseDeclarations()

	/**
	 * Return the raw CSS file content for download.
	 *
	 * @return string The raw file content, or an empty :root {} if the file does not exist.
	 *
	 * @spec openspec/changes/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-34
	 */
	public function getRawContent(): string {
		$path = $this->getFilePath();
		if (file_exists($path) === false) {
			return self::CSS_HEADER . PHP_EOL . ':root {}' . PHP_EOL;
		}

		$content = file_get_contents(filename: $path);
		if ($content === false) {
			return '';
		}

		return $content;
	}//end getRawContent()
}//end class
