<?php

/**
 * NL Design Freeform Custom CSS Persistence.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/specs/custom-css-freeform/spec.md
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCA\Thematiq\AppInfo\Application;
use OCA\Thematiq\Service\RuntimeFile\RuntimeFileStore;
use OCP\IAppConfig;
use RuntimeException;

/**
 * Reads and writes the freeform custom CSS layer.
 *
 * The freeform layer is deliberately a SEPARATE file from
 * `custom-overrides.css`. That file is machine-generated by the token editor
 * and its specification forbids anything but a single `:root` block, so
 * mixing hand-authored rules into it would both break that contract and
 * corrupt the editor's round-trip parse.
 *
 * Writes go through CustomCssValidator first. The file is kept in app data
 * through the RuntimeFileStore, never in the signed app directory, and the
 * store replaces it in one write.
 *
 * @spec openspec/specs/custom-css-freeform/spec.md
 */
class CustomCssService {

	/**
	 * Appconfig key holding the enable flag.
	 *
	 * @var string
	 */
	public const ENABLED_KEY = 'custom_css_enabled';

	/**
	 * The runtime file name of the freeform stylesheet.
	 *
	 * @var string
	 */
	public const FILE = 'css/custom-css.css';

	/**
	 * Where the freeform stylesheet is stored.
	 *
	 * @var RuntimeFileStore
	 */
	private RuntimeFileStore $store;

	/**
	 * App configuration, backing the enable flag.
	 *
	 * @var IAppConfig
	 */
	private IAppConfig $appConfig;

	/**
	 * The sanitiser applied before any write.
	 *
	 * @var CustomCssValidator
	 */
	private CustomCssValidator $validator;

	/**
	 * Constructor.
	 *
	 * @param RuntimeFileStore $store Where the freeform stylesheet is stored.
	 * @param IAppConfig $appConfig App configuration.
	 * @param CustomCssValidator $validator The freeform CSS sanitiser.
	 */
	public function __construct(
		RuntimeFileStore $store,
		IAppConfig $appConfig,
		CustomCssValidator $validator,
	) {
		$this->store = $store;
		$this->appConfig = $appConfig;
		$this->validator = $validator;

	}//end __construct()


	/**
	 * Whether the freeform layer is switched on.
	 *
	 * Defaults to OFF: an instance that never opts in must never load the
	 * layer, even if a file happens to exist on disk.
	 *
	 * @return boolean True when enabled.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function isEnabled(): bool {
		return $this->appConfig->getValueString(Application::APP_ID, self::ENABLED_KEY, '0') === '1';
	}//end isEnabled()

	/**
	 * Switch the freeform layer on or off.
	 *
	 * @param bool $enabled Desired state.
	 *
	 * @return void
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function setEnabled(bool $enabled): void {
		$value = '0';
		if ($enabled === true) {
			$value = '1';
		}

		$this->appConfig->setValueString(Application::APP_ID, self::ENABLED_KEY, $value);

	}//end setEnabled()

	/**
	 * Read the stored freeform CSS.
	 *
	 * A missing file is not an error — it is the fresh-install state — and
	 * yields an empty string.
	 *
	 * @return string The stored CSS, or '' when nothing is stored.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function read(): string {
		return ($this->store->read(name: self::FILE) ?? '');
	}//end read()

	/**
	 * Validate and persist freeform CSS.
	 *
	 * @param string $css The admin-submitted CSS.
	 *
	 * @return string[] Validation errors. EMPTY means the CSS was written;
	 *                  a non-empty array means NOTHING was written.
	 *
	 * @throws RuntimeException When the file cannot be written.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function write(string $css): array {
		$errors = $this->validator->validate(css: $css);
		if (empty($errors) === false) {
			return $errors;
		}

		$document = "/* NL Design — freeform custom CSS. Authored by an administrator. */\n" . $css . "\n";
		$this->store->write(name: self::FILE, content: $document);

		return [];
	}//end write()

	/**
	 * Whether a non-empty freeform stylesheet is stored.
	 *
	 * Used by the injection layer so an enabled-but-empty configuration does
	 * not emit a pointless <link>.
	 *
	 * @return boolean True when there is something to serve.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function hasContent(): bool {
		return trim($this->read()) !== '';
	}//end hasContent()
}//end class
