<?php

/**
 * NL Design Freeform Custom CSS Persistence.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/specs/custom-css-freeform/spec.md
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCA\Thematiq\AppInfo\Application;
use OCP\App\IAppManager;
use OCP\IAppConfig;
use RuntimeException;

/**
 * Reads and writes the freeform custom CSS layer.
 *
 * The freeform layer is deliberately a SEPARATE file from
 * `custom-overrides.css`. That file is machine-generated by the token editor
 * and its specification forbids anything but a single `:root` block, so
 * mixing hand-authored rules into it would both break that contract and
 * corrupt the editor's round-trip parse.
 *
 * Writes go through CustomCssValidator first and are atomic (temp file +
 * rename) so a partial write can never be served to browsers.
 *
 * @spec openspec/specs/custom-css-freeform/spec.md
 */
class CustomCssService {

	/**
	 * Appconfig key holding the enable flag.
	 *
	 * @var string
	 */
	public const ENABLED_KEY = 'custom_css_enabled';

	/**
	 * The comment written above the administrator's CSS in the file.
	 *
	 * It belongs to the file, not to the CSS: read() strips it again, so the
	 * editor shows exactly what the administrator typed and a second save does
	 * not stack a second header on top of the first.
	 *
	 * @var string
	 */
	public const FILE_HEADER = "/* NL Design — freeform custom CSS. Authored by an administrator. */\n";

	/**
	 * The app manager, used to resolve the app's css/ directory.
	 *
	 * @var IAppManager
	 */
	private IAppManager $appManager;

	/**
	 * App configuration, backing the enable flag.
	 *
	 * @var IAppConfig
	 */
	private IAppConfig $appConfig;

	/**
	 * The sanitiser applied before any write.
	 *
	 * @var CustomCssValidator
	 */
	private CustomCssValidator $validator;

	/**
	 * Constructor.
	 *
	 * @param IAppManager $appManager The app manager.
	 * @param IAppConfig $appConfig App configuration.
	 * @param CustomCssValidator $validator The freeform CSS sanitiser.
	 */
	public function __construct(
		IAppManager $appManager,
		IAppConfig $appConfig,
		CustomCssValidator $validator,
	) {
		$this->appManager = $appManager;
		$this->appConfig = $appConfig;
		$this->validator = $validator;

	}//end __construct()

	/**
	 * Absolute path to the freeform stylesheet.
	 *
	 * @return string The CSS file path.
	 */
	private function getFilePath(): string {
		return $this->appManager->getAppPath(Application::APP_ID) . '/css/custom-css.css';
	}//end getFilePath()

	/**
	 * Whether the freeform layer is switched on.
	 *
	 * Defaults to OFF: an instance that never opts in must never load the
	 * layer, even if a file happens to exist on disk.
	 *
	 * @return boolean True when enabled.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function isEnabled(): bool {
		return $this->appConfig->getValueString(Application::APP_ID, self::ENABLED_KEY, '0') === '1';
	}//end isEnabled()

	/**
	 * Switch the freeform layer on or off.
	 *
	 * @param bool $enabled Desired state.
	 *
	 * @return void
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function setEnabled(bool $enabled): void {
		$value = '0';
		if ($enabled === true) {
			$value = '1';
		}

		$this->appConfig->setValueString(Application::APP_ID, self::ENABLED_KEY, $value);

	}//end setEnabled()

	/**
	 * Read the stored freeform CSS.
	 *
	 * A missing file is not an error — it is the fresh-install state — and
	 * yields an empty string.
	 *
	 * @return string The CSS as the administrator wrote it, without the file
	 *                header write() adds, or '' when nothing is stored.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function read(): string {
		$path = $this->getFilePath();
		if (file_exists($path) === false) {
			return '';
		}

		$contents = file_get_contents($path);
		if ($contents === false) {
			return '';
		}

		// Undo what write() added around the CSS. Earlier releases read the
		// header back as part of the CSS, so every save stacked one more; the
		// loop peels all of them, and the next save leaves a single one. A file
		// without the header (hand-edited, or older) is returned as it is.
		while (str_starts_with($contents, self::FILE_HEADER) === true) {
			$contents = substr($contents, strlen(self::FILE_HEADER));
			if (str_ends_with($contents, "\n") === true) {
				$contents = substr($contents, 0, -1);
			}
		}

		return $contents;
	}//end read()

	/**
	 * Validate and persist freeform CSS.
	 *
	 * @param string $css The admin-submitted CSS.
	 *
	 * @return string[] Validation errors. EMPTY means the CSS was written;
	 *                  a non-empty array means NOTHING was written.
	 *
	 * @throws RuntimeException When the file cannot be written.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function write(string $css): array {
		$errors = $this->validator->validate(css: $css);
		if (empty($errors) === false) {
			return $errors;
		}

		$path = $this->getFilePath();
		$tmpPath = $path . '.tmp';

		$document = self::FILE_HEADER . $css . "\n";

		if (file_put_contents(filename: $tmpPath, data: $document) === false) {
			throw new RuntimeException(
				message: 'Could not write ' . $tmpPath . '. Ensure the web server has write access to the css/ directory.'
			);
		}

		if (rename(from: $tmpPath, to: $path) === false) {
			if (file_exists(filename: $tmpPath) === true) {
				unlink(filename: $tmpPath);
			}

			throw new RuntimeException(message: 'Temp file could not be renamed to ' . $path . '.');
		}

		return [];
	}//end write()

	/**
	 * Whether a non-empty freeform stylesheet is present on disk.
	 *
	 * Used by the injection layer so an enabled-but-empty configuration does
	 * not emit a pointless <link>.
	 *
	 * @return boolean True when there is something to serve.
	 *
	 * @spec openspec/specs/custom-css-freeform/spec.md
	 */
	public function hasContent(): bool {
		return trim($this->read()) !== '';
	}//end hasContent()
}//end class
