<?php

/**
 * Thematiq overrides CSS builder.
 *
 * Builds the content of a custom overrides file: the editor's values in `:root`
 * with `!important`, the thematiq twin of each motion token, the motion tokens again
 * on body for a user who chose a theme, the dark value of each
 * brand-layer colour in the two dark scopes, and the administrator's own tokens
 * after them without `!important`. Split out of {@see CustomOverridesService},
 * which keeps the file reading and writing.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/changes/archive/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 * @spec openspec/specs/own-tokens/spec.md#requirement-own-tokens-are-served-in-both-themes
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

/**
 * The CSS of one overrides file.
 *
 * @spec openspec/changes/archive/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
 */
class OverridesCssBuilder {

	/**
	 * The scope of a user whose system is dark and who chose no theme (as in
	 * the generated dark stylesheets).
	 *
	 * @var string
	 */
	private const SYSTEM_DARK_SELECTOR = 'body:not([data-theme-light]):not([data-theme-dark])'
		. ':not([data-theme-light-highcontrast]):not([data-theme-dark-highcontrast])';

	/**
	 * The scope of a user who chose the dark theme (as in the generated dark stylesheets).
	 *
	 * @var string
	 */
	private const CHOSEN_DARK_SELECTOR = 'body[data-theme-dark],' . PHP_EOL . 'body[data-themes*=dark]';

	/**
	 * The scope of every user but one who chose reduced motion. A chosen theme
	 * declares Nextcloud's durations on body, so the motion overrides go there
	 * too; the reduced-motion theme sets them to 0 on purpose and keeps that.
	 *
	 * @var string
	 */
	private const MOTION_SELECTOR = 'body:not([data-theme-reduced-motion])';

	/**
	 * The CSS file header comment.
	 *
	 * @var string
	 */
	public const CSS_HEADER = '/* NL Design — custom token overrides. Generated by theme editor. Do not edit manually. */';

	/**
	 * The motion tokens the editor sets, and the thematiq name each one also writes, so both
	 * Nextcloud's components and anything reading the thematiq name follow the same speed.
	 *
	 * @var array<string, string>
	 */
	public const MOTION_TWINS = [
		'--animation-quick' => '--nldesign-animation-quick',
		'--animation-slow' => '--nldesign-animation-slow',
	];

	/**
	 * Label and fill pairs among Nextcloud's own variables that the dark scopes
	 * repair, as DarkPaletteService::CONTROL_PAIRS does for the generated dark
	 * stylesheets. Each override derives its dark value on its own, so a white
	 * label took the text clamp to mid-grey #9e9e9e on a fill that turned light
	 * blue (thematiq#953). A pair is repaired only when the editor overrides
	 * both sides; the other side otherwise comes from elsewhere and is not
	 * this file's to measure.
	 *
	 * @var array<int, array{fg: string, bg: string, threshold: float}>
	 */
	public const DARK_PAIRS = [
		['fg' => '--color-primary-text', 'bg' => '--color-primary', 'threshold' => 4.5],
		['fg' => '--color-primary-element-text', 'bg' => '--color-primary-element', 'threshold' => 4.5],
		['fg' => '--color-primary-light-text', 'bg' => '--color-primary-light', 'threshold' => 4.5],
		['fg' => '--color-primary-element-light-text', 'bg' => '--color-primary-element-light', 'threshold' => 4.5],
	];

	/**
	 * Constructor.
	 *
	 * @param DarkPaletteService $darkPalette Derives each colour override's dark value.
	 * @param TokenValueValidator $values Says which tokens get a dark value.
	 */
	public function __construct(
		private readonly DarkPaletteService $darkPalette,
		private readonly TokenValueValidator $values,
	) {
	}//end __construct()

	/**
	 * Build the file content.
	 *
	 * @param array<string, string> $tokens Editor token => light value (registry names only).
	 * @param array<string, string> $darkTokens Editor token => the administrator's own dark value.
	 * @param OwnTokenCss|null $own The administrator's own tokens, rendered after the editor's.
	 *
	 * @return string The CSS file content.
	 *
	 * @spec openspec/changes/archive/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-32
	 * @spec openspec/specs/own-tokens/spec.md#requirement-own-tokens-are-served-in-both-themes
	 */
	public function build(array $tokens, array $darkTokens = [], ?OwnTokenCss $own = null): string {
		$own = ($own ?? new OwnTokenCss());
		$lines = array_merge(
			$this->declarationLines(tokens: $this->withMotionTwins(tokens: $tokens), important: true),
			$own->lightLines()
		);
		if ($lines === []) {
			return self::CSS_HEADER . PHP_EOL . ':root {}' . PHP_EOL;
		}

		$css = self::CSS_HEADER . PHP_EOL . ':root {' . PHP_EOL . implode(PHP_EOL, $lines) . PHP_EOL . '}' . PHP_EOL;

		// A user who chose a theme, dark or light, gets Nextcloud's durations
		// declared on body (`[data-theme-dark] { --animation-quick: 100ms }`),
		// which a :root value never reaches (#937).
		$motionLines = $this->declarationLines(tokens: array_intersect_key($tokens, self::MOTION_TWINS), important: true);
		if ($motionLines !== []) {
			$css .= self::MOTION_SELECTOR . ' {' . PHP_EOL . implode(PHP_EOL, $motionLines) . PHP_EOL . '}' . PHP_EOL;
		}

		// The administrator's own dark value replaces a derived one, and is the
		// only dark value of a settable or internal colour, which derive none.
		$ownDark = array_filter(
			$darkTokens,
			fn (string $name): bool => isset($tokens[$name]) === true && $this->values->hasDarkValueFor(name: $name) === true,
			ARRAY_FILTER_USE_KEY
		);
		$darkLines = array_merge(
			$this->declarationLines(tokens: array_merge($this->darkValues(tokens: $tokens), $ownDark), important: true),
			$own->darkLines()
		);
		if ($darkLines === []) {
			return $css;
		}

		// The same two scopes the generated dark stylesheets use. A user who
		// chose the dark theme gets Nextcloud's dark colours declared on body,
		// which a :root value never reaches; a body-level declaration wins for
		// both kinds of dark user.
		return $css . '@media (prefers-color-scheme: dark) {' . PHP_EOL
			. '	' . self::SYSTEM_DARK_SELECTOR . ' {' . PHP_EOL
			. '	' . implode(PHP_EOL . '	', $darkLines) . PHP_EOL
			. '	}' . PHP_EOL
			. '}' . PHP_EOL
			. self::CHOSEN_DARK_SELECTOR . ' {' . PHP_EOL
			. implode(PHP_EOL, $darkLines) . PHP_EOL
			. '}' . PHP_EOL;
	}//end build()

	/**
	 * The dark value of every brand-layer colour override: derived as the
	 * generated dark stylesheets derive it, or the light value when it is not
	 * a colour literal, so both kinds of dark user still see the same thing.
	 * Label and fill pairs in {@see self::DARK_PAIRS} are then repaired.
	 *
	 * Only the brand layer (Nextcloud's own variables) is split, because only
	 * those does Nextcloud re-declare on body for a chosen theme. Component
	 * tokens are left out: both kinds of dark user already get the same body
	 * value from the generated dark stylesheet, and a body-level copy here would
	 * outrank the primary-lock layer, which locks them at :root.
	 *
	 * @param array<string, string> $tokens Token name => light value.
	 *
	 * @return array<string, string> Colour token name => dark value.
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 *
	 * @spec openspec/specs/dark-mode/spec.md#requirement-editor-overrides-apply-the-same-way-for-every-dark-user
	 */
	public function darkValues(array $tokens): array {
		$registry = TokenRegistry::getTokens();
		$dark = [];
		foreach ($tokens as $name => $value) {
			// A settable variable gets no derived dark value: it keeps
			// Nextcloud's own in dark unless a dark value is given.
			if ($this->values->hasDarkValue(meta: ($registry[$name] ?? [])) === false || ($registry[$name]['settable'] ?? false) === true) {
				continue;
			}

			$dark[$name] = ($this->darkPalette->deriveDarkValue(token: $name, lightValue: $value, context: $tokens) ?? $value);
		}

		// The same repair the generated dark stylesheets get. An administrator's
		// own dark value is not in this map, so it is never rewritten.
		return $this->darkPalette->verifyAndRepair(declarations: $dark, pairs: self::DARK_PAIRS)['declarations'];
	}//end darkValues()

	/**
	 * The tokens plus the thematiq twin of each motion token, with the same value.
	 *
	 * @param array<string, string> $tokens The editor's tokens.
	 *
	 * @return array<string, string> The tokens to write into `:root`.
	 *
	 * @spec openspec/specs/token-editor-ui/spec.md#requirement-motion-tokens-are-typed-and-reach-every-transition
	 */
	private function withMotionTwins(array $tokens): array {
		foreach (self::MOTION_TWINS as $name => $twin) {
			if (isset($tokens[$name]) === true) {
				$tokens[$twin] = $tokens[$name];
			}
		}

		return $tokens;
	}//end withMotionTwins()

	/**
	 * Build individual CSS declaration lines from a token map.
	 *
	 * @param array<string, string> $tokens Token name => value pairs.
	 * @param bool $important Whether each line carries `!important`.
	 *
	 * @return array<string> List of CSS declaration lines.
	 *
	 * @spec openspec/changes/archive/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
	 *
	 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design
	 */
	public static function declarationLines(array $tokens, bool $important): array {
		$suffix = ';';
		if ($important === true) {
			$suffix = ' !important;';
		}

		$lines = [];
		foreach ($tokens as $name => $value) {
			// Reject any value containing CSS injection characters.
			if (self::isUnsafeValue(value: $value) === true) {
				continue;
			}

			// A settable Nextcloud variable is stored as its `--nldesign-nc-*`
			// token: the theme scopes read the token, and a plain declaration
			// of the variable on :root would lose to their body-level one.
			$safeName = preg_replace('/[^a-zA-Z0-9\-]/', '', (TokenRegistry::settableToken(tokenName: $name) ?? $name));

			// Strip any pre-existing !important the caller may have included; it is
			// re-applied uniformly so the round-trip stays canonical.
			$safeValue = trim((string)preg_replace('/\s*!\s*important\s*$/i', '', str_replace(["\n", "\r"], '', $value)));

			// Editor overrides carry !important so they win the cascade: the
			// nldesign design-system stylesheets re-declare every editable token
			// with !important, and Nextcloud core theming overrides tokens like
			// --color-primary. The file only ever holds tokens the admin set, so
			// this does not blanket-!important the registry. Own tokens do not
			// need it: nothing else declares them.
			$lines[] = '  ' . $safeName . ': ' . $safeValue . $suffix;
		}

		return $lines;
	}//end declarationLines()

	/**
	 * Tell whether a value carries a character that would break out of its block.
	 *
	 * @param string $value The token value.
	 *
	 * @return bool True when the writer drops the value.
	 *
	 * @spec openspec/changes/archive/retrofit-2026-05-24-annotate-nldesign/tasks.md#task-33
	 */
	public static function isUnsafeValue(string $value): bool {
		return preg_match('/[{};]|\/\*|\*\//', $value) === 1;
	}//end isUnsafeValue()
}//end class
