<?php

/**
 * Thematiq Token Reference Service.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/specs/token-reference/spec.md
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCA\Thematiq\Service\RuntimeFile\RuntimeFileStore;
use OCA\Thematiq\Service\RuntimeFile\SetFileReader;

/**
 * Renders the token reference of one token set, as Markdown (the docs site and the download)
 * or as an HTML page (the in-app view): every token the set declares or inherits from the
 * defaults layer, its value and dark-mode value, where it comes from, and what it paints.
 * Output is deterministic: sorted, no timestamps.
 *
 * @spec openspec/specs/token-reference/spec.md
 *
 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design.
 */
class TokenReferenceService {

	/**
	 * The stylesheets that turn `--nldesign-*` tokens into what Nextcloud and the components read.
	 *
	 * @var array<int, string>
	 */
	private const BRIDGES = ['css/systems/nldesign/overrides.css', 'css/systems/nldesign/utrecht-bridge.css'];

	/**
	 * Row groups in page order: heading, and the name fragments that put a token in it.
	 *
	 * @var array<string, array<int, string>>
	 */
	private const GROUPS = [
		'Colours (Kleuren)' => ['color', 'colour'],
		'Typography (Typografie)' => ['font', 'line-height', 'letter-spacing', 'text-'],
		'Spacing and shape (Ruimte en vorm)' => ['space', 'spacing', 'radius', 'border', 'size', 'width', 'height', 'gap', 'padding', 'margin'],
		'Other tokens (Overige tokens)' => [''],
	];

	/**
	 * The heading of the tokens nothing reads.
	 *
	 * @var string
	 */
	private const UNREAD = 'Tokens nothing reads (Tokens die niets leest)';

	/**
	 * Constructor.
	 *
	 * @param ShippedTokenSetAuditService $audit The contrast audit, for the summary line.
	 * @param CssParserService $parser The CSS parser.
	 * @param TokenReferenceCells $cells The cell formatter.
	 * @param RuntimeFileStore|null $store Where uploaded sets are kept.
	 * @param SetFileReader $files Reads a set's file from the release or the store.
	 */
	public function __construct(
		private ShippedTokenSetAuditService $audit,
		private CssParserService $parser,
		private TokenReferenceCells $cells = new TokenReferenceCells(),
		private ?RuntimeFileStore $store = null,
		private SetFileReader $files = new SetFileReader(),
	) {
	}//end __construct()

	/**
	 * Render the reference of one set.
	 *
	 * @param string $appPath The app root.
	 * @param array<string, mixed> $set The set: `id`, `name`, `theming`.
	 * @param string $format `md`, `md-plain` or `html`. `md-plain` is Markdown without swatch images:
	 *                       the docs site renders them, but a downloaded file is read as text, where
	 *                       each one is a long data URL.
	 *
	 * @return string The reference.
	 *
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-docs-site-has-a-reference-page-per-shipped-set
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-reference-does-not-rely-on-colour-alone
	 */
	public function render(string $appPath, array $set, string $format): string {
		$model = $this->model(appPath: $appPath, set: $set);
		if ($format === 'html') {
			return $this->html(model: $model);
		}

		return $this->markdown(model: $model, format: $format);
	}//end render()

	/**
	 * Every docs page: one per shipped set with a token file, and an index.
	 *
	 * @param string $appPath The app root.
	 *
	 * @return array<string, string> File name under docs/reference/token-sets/ => content.
	 *
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-docs-site-has-a-reference-page-per-shipped-set
	 */
	public function docsPages(string $appPath): array {
		$manifest = json_decode((string)file_get_contents($appPath . '/token-sets.json'), true);
		if (is_array($manifest) === false) {
			$manifest = [];
		}

		$sets = [];
		foreach ($manifest as $set) {
			if (is_array($set) === false || is_string($set['id'] ?? null) === false) {
				continue;
			}

			if (is_file($appPath . '/css/tokens/' . $set['id'] . '.css') === true) {
				$sets[$set['id']] = $set;
			}
		}

		ksort($sets);
		$pages = [];
		$index = [
			'<!-- GENERATED by TokenReferenceService, do not edit by hand. Regenerate with: composer docs:token-reference -->',
			'',
			'# Token sets',
			'',
			'The tokens of every shipped token set: the value, the dark-mode value, whether it comes from the set'
				. ' or from the defaults layer, and what it paints. Signed-in users also find the reference of custom sets'
				. ' in Nextcloud, under Settings > Administration > Theming.',
			'',
		];
		foreach ($sets as $id => $set) {
			$pages[$id . '.md'] = $this->render(appPath: $appPath, set: $set, format: 'md');
			$index[] = '- [' . $this->cells->mdText(text: (string)($set['name'] ?? $id)) . '](./' . $id . '.md) `' . $id . '`';
		}

		$pages['index.md'] = implode("\n", $index) . "\n";
		ksort($pages);

		return $pages;
	}//end docsPages()

	/**
	 * Resolve the rows of one set.
	 *
	 * @param string $appPath The app root.
	 * @param array<string, mixed> $set The set.
	 *
	 * @return array{id: string, name: string, declared: int, inherited: int, contrast: string, groups: array<string, array<int, array<string, mixed>>>}
	 */
	private function model(string $appPath, array $set): array {
		$id = (string)$set['id'];
		$defaults = $this->parseFile(path: $appPath . '/css/systems/nldesign/defaults.css');
		$own = $this->parser->parseRootBlock(css: (string)$this->files->read(store: $this->store, appPath: $appPath, name: 'css/tokens/' . $id . '.css'));
		$dark = $this->parseAnyCss(css: (string)$this->files->read(store: $this->store, appPath: $appPath, name: 'css/tokens/dark/' . $id . '.css'));
		$consumers = $this->consumers(appPath: $appPath);

		$names = array_unique(array_merge(array_keys($defaults), array_keys($own)));
		sort($names);
		$groups = array_fill_keys(array_merge(array_keys(self::GROUPS), [self::UNREAD]), []);
		foreach ($names as $name) {
			$declared = array_key_exists($name, $own);
			$source = 'defaults';
			if ($declared === true) {
				$source = 'this set';
			}

			$row = [
				'name' => $name,
				'value' => ($own[$name] ?? $defaults[$name]),
				'dark' => ($dark[$name] ?? ''),
				'source' => $source,
				'paints' => ($consumers[$name] ?? []),
			];
			$group = $this->groupOf(name: $name);
			if ($declared === true && array_key_exists($name, $defaults) === false && $row['paints'] === []) {
				$group = self::UNREAD;
			}

			$groups[$group][] = $row;
		}

		return [
			'id' => $id,
			'name' => (string)($set['name'] ?? $id),
			'declared' => count($own),
			'inherited' => count(array_diff_key($defaults, $own)),
			'contrast' => $this->contrastLine(appPath: $appPath, id: $id, theming: (array)($set['theming'] ?? [])),
			'groups' => array_filter($groups),
		];
	}//end model()

	/**
	 * The `:root` declarations of a file, or none when it is absent.
	 *
	 * @param string $path The file.
	 *
	 * @return array<string, string> Name => value.
	 */
	private function parseFile(string $path): array {
		if (is_file($path) === false) {
			return [];
		}

		return $this->parser->parseRootBlock(css: (string)file_get_contents($path));
	}//end parseFile()

	/**
	 * Every declaration in a stylesheet, first one wins, whatever block it sits in.
	 *
	 * @param string $css The stylesheet.
	 *
	 * @return array<string, string> Name => value.
	 *
	 * @spec openspec/specs/runtime-file-storage/spec.md
	 */
	private function parseAnyCss(string $css): array {
		preg_match_all('/(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]+);/', $css, $matches, PREG_SET_ORDER);
		$result = [];
		foreach ($matches as $match) {
			if (isset($result[$match[1]]) === false) {
				$result[$match[1]] = trim($match[2]);
			}
		}

		return $result;
	}//end parseAnyCss()

	/**
	 * Which properties read each `--nldesign-*` token, with the registry label where there is one.
	 *
	 * @param string $appPath The app root.
	 *
	 * @return array<string, array<int, string>> Token => sorted, unique consumer descriptions.
	 */
	private function consumers(string $appPath): array {
		$labels = TokenRegistry::getTokens();
		$map = [];
		foreach (self::BRIDGES as $bridge) {
			if (is_file($appPath . '/' . $bridge) === false) {
				continue;
			}

			$css = (string)file_get_contents($appPath . '/' . $bridge);
			preg_match_all('/(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]*)/', $css, $matches, PREG_SET_ORDER);
			foreach ($matches as $match) {
				preg_match_all('/var\(\s*(--nldesign-[A-Za-z0-9_-]+)/', $match[2], $reads);
				foreach ($reads[1] as $token) {
					$map[$token][] = (string)($labels[$match[1]]['label'] ?? '`' . $match[1] . '`');
				}
			}
		}

		foreach ($map as $token => $list) {
			$list = array_values(array_unique($list));
			sort($list);
			$map[$token] = $list;
		}

		return $map;
	}//end consumers()

	/**
	 * The group heading of a token.
	 *
	 * @param string $name The token name.
	 *
	 * @return string The heading.
	 */
	private function groupOf(string $name): string {
		foreach (self::GROUPS as $heading => $fragments) {
			foreach ($fragments as $fragment) {
				if ($fragment === '' || str_contains($name, $fragment) === true) {
					return $heading;
				}
			}
		}

		return 'Other tokens (Overige tokens)';
	}//end groupOf()

	/**
	 * The contrast summary of the set.
	 *
	 * @param string $appPath The app root.
	 * @param string $id The set id.
	 * @param array<string, mixed> $theming The set's theming block.
	 *
	 * @return string The sentence.
	 */
	private function contrastLine(string $appPath, string $id, array $theming): string {
		$result = $this->audit->auditSet(appPath: $appPath, id: $id, theming: $theming);

		return sprintf(
			'Contrast: primary text on primary %s, primary on background %s (%s).',
			$this->ratio(value: $result['textRatio']),
			$this->ratio(value: $result['uiRatio']),
			$result['verdict']
		);
	}//end contrastLine()

	/**
	 * A ratio as text.
	 *
	 * @param float|null $value The ratio.
	 *
	 * @return string `4.62:1`, or `not evaluated`.
	 */
	private function ratio(?float $value): string {
		if ($value === null) {
			return 'not evaluated';
		}

		return number_format($value, 2) . ':1';
	}//end ratio()

	/**
	 * The Markdown page.
	 *
	 * @param array<string, mixed> $model The resolved rows.
	 * @param string $format `md` with swatch images, or `md-plain` without.
	 *
	 * @return string Markdown.
	 */
	private function markdown(array $model, string $format): string {
		$cell = 'mdValue';
		if ($format === 'md-plain') {
			$cell = 'mdPlainValue';
		}

		$lines = [
			'<!-- GENERATED by TokenReferenceService, do not edit by hand. Regenerate with: composer docs:token-reference -->',
			'',
			'# ' . $this->cells->mdText(text: $model['name']),
			'',
			sprintf('Token set `%s`: %d declared by this set, %d from the defaults layer.', $model['id'], $model['declared'], $model['inherited']),
			'',
			$model['contrast'],
		];
		foreach ($model['groups'] as $heading => $rows) {
			array_push($lines, '', '## ' . $heading, '', '| Token | Value | Dark mode | Source | Paints |', '|---|---|---|---|---|');
			foreach ($rows as $row) {
				$cells = [
					'`' . $row['name'] . '`',
					$this->cells->$cell(value: $row['value']),
					$this->cells->$cell(value: $row['dark']),
					$row['source'],
					$this->cells->paints(list: $row['paints']),
				];
				$lines[] = str_replace('|  |', '| |', '| ' . implode(' | ', $cells) . ' |');
			}
		}

		return implode("\n", $lines) . "\n";
	}//end markdown()

	/**
	 * The HTML page.
	 *
	 * @param array<string, mixed> $model The resolved rows.
	 *
	 * @return string HTML.
	 */
	private function html(array $model): string {
		$name = $this->cells->esc(text: $model['name']);
		$out = '<!DOCTYPE html>' . "\n" . '<html lang="en">' . "\n" . '<head>' . "\n" . '<meta charset="utf-8">' . "\n"
			. '<title>' . $name . ' token reference</title>' . "\n"
			. '<style>body{font-family:sans-serif;color:#1a1a1a;background:#fff;margin:2em;line-height:1.5}'
			. 'table{border-collapse:collapse;margin-bottom:2em}th,td{border:1px solid #767676;padding:4px 8px;text-align:left;vertical-align:top}'
			. '.swatch{display:inline-block;width:1em;height:1em;border:1px solid #767676;vertical-align:middle}'
			. 'summary{cursor:pointer;font-weight:bold}</style>' . "\n" . '</head>' . "\n" . '<body>' . "\n" . '<main>' . "\n"
			. '<h1>' . $name . '</h1>' . "\n"
			. '<p>' . sprintf(
				'Token set <code>%s</code>: %d declared by this set, %d from the defaults layer.',
				$this->cells->esc(text: $model['id']),
				$model['declared'],
				$model['inherited']
			) . '</p>' . "\n"
			. '<p>' . $this->cells->esc(text: $model['contrast']) . '</p>' . "\n";
		foreach ($model['groups'] as $heading => $rows) {
			$table = $this->htmlTable(rows: $rows);
			if ($heading === self::UNREAD) {
				$out .= '<details>' . "\n" . '<summary>' . $this->cells->esc(text: $heading) . '</summary>' . "\n" . $table . '</details>' . "\n";
				continue;
			}

			$out .= '<h2>' . $this->cells->esc(text: $heading) . '</h2>' . "\n" . $table;
		}

		return $out . '</main>' . "\n" . '</body>' . "\n" . '</html>' . "\n";
	}//end html()

	/**
	 * One HTML table.
	 *
	 * @param array<int, array<string, mixed>> $rows The rows.
	 *
	 * @return string HTML.
	 */
	private function htmlTable(array $rows): string {
		$out = '<table>' . "\n" . '<thead><tr><th scope="col">Token</th><th scope="col">Value</th><th scope="col">Dark mode</th>'
			. '<th scope="col">Source</th><th scope="col">Paints</th></tr></thead>' . "\n" . '<tbody>' . "\n";
		foreach ($rows as $row) {
			$out .= '<tr><td><code>' . $this->cells->esc(text: $row['name']) . '</code></td><td>' . $this->cells->htmlValue(value: $row['value']) . '</td><td>'
				. $this->cells->htmlValue(value: $row['dark']) . '</td><td>' . $row['source'] . '</td><td>'
				. $this->cells->esc(text: str_replace('`', '', $this->cells->paints(list: $row['paints']))) . '</td></tr>' . "\n";
		}

		return $out . '</tbody>' . "\n" . '</table>' . "\n";
	}//end htmlTable()

}//end class
