<?php

/**
 * NL Design System theme to Nextcloud token set converter.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/changes/nlds-theme-converter/specs/token-set-converter/spec.md
 */

declare(strict_types=1);

namespace OCA\Thematiq\Service;

use OCP\App\IAppManager;
use Psr\Log\LoggerInterface;
use RuntimeException;

/**
 * Turn a published design-system theme into a Nextcloud token set.
 *
 * The whole mapping lives in
 * `scripts/mapping/nlds-to-nextcloud.json` as DATA, and this service is one of
 * two thin runtimes over it (the other being `js/lib/tokenConverter.js`), so
 * the admin upload path and the CLI cannot drift apart. The table's SHA-256 is
 * written into every emitted file's provenance block, which is how a set
 * generated by an older table is spotted without running anything.
 *
 * FOUR ACCEPTED INPUTS, detected from the CONTENT and never from a file name,
 * because the primary surface is a paste that has no file name:
 *
 *  - A: built theme CSS — one or more class-scoped blocks of custom properties
 *       (`.acme-theme { --utrecht-*: …; --acme-*: …; }`), values may be `var()`
 *       chains. This is what a Style Dictionary theme package publishes as
 *       `dist/design-tokens.css` and is the primary target.
 *  - B: a W3C DTCG document (`$value`/`$type`, `{a.b.c}` aliases). Routed
 *       straight to `DesignTokensMapper`, which already owns those semantics —
 *       there is deliberately no second DTCG parser here.
 *  - C: a Style Dictionary `tokens.json` tree (nested `value` leaves).
 *  - D: an existing `:root`-scoped `--nldesign-*` token set, re-converted in
 *       ADD-ONLY mode so a hand-chosen value is never overwritten.
 *
 * WHAT COMES BACK is `{css, manifestEntry, report, inputKind, counts}`. The
 * report is the contract that matters most: every source token ends up in it
 * with an action of `applied`, `adapted`, `skipped` or `kept`, and every
 * non-`applied` entry carries a reason code that exists in the table. Nothing
 * is dropped silently, because an admin who pastes a 697-declaration theme and
 * gets 26 tokens back needs to be told what happened to the other 671.
 *
 * @phpstan-type ReportEntry array{source: string, target: string, action: string, reason: string|null, value: string|null, original?: string}
 * @psalm-type   ReportEntry array{source: string, target: string, action: string, reason: string|null, value: string|null, original?: string}
 *
 * @spec openspec/changes/nlds-theme-converter/specs/token-set-converter/spec.md
 */
class TokenSetConverterService {

	/**
	 * Component-layer prefixes emitted verbatim into section 2.
	 *
	 * `css/systems/nldesign/utrecht-bridge.css` reads these into
	 * `--nldesign-component-*`, and Conduction's own apps plus
	 * `@conduction/nextcloud-vue` read them directly, which is why they are
	 * kept in the file even when Nextcloud itself has no such component.
	 *
	 * `--conduction-` belongs here for the same reason the others do, and
	 * leaving it out was destructive: an OpenWOO-shaped theme carries ~266
	 * `--conduction-*` tokens (logos, cards, pagination, tooltips, top-nav) and
	 * every one of them was being renamed into the brand palette, where nothing
	 * reads it. `css/tokens/opencatalogi.css` declares 266 of them verbatim and
	 * `css/tokens/conduction.css` 103, which is what a correct set looks like.
	 *
	 * `--conduction-` belongs here for the same reason the others do, and
	 * leaving it out was destructive: an OpenWOO-shaped theme carries ~266
	 * `--conduction-*` tokens (logos, cards, pagination, tooltips, top-nav) and
	 * every one of them was being renamed into the brand palette, where nothing
	 * reads it. `css/tokens/opencatalogi.css` declares 266 of them verbatim and
	 * `css/tokens/conduction.css` 103, which is what a correct set looks like.
	 *
	 * This list decides only what a kept token is CALLED, never what it means.
	 * Meaning comes from {@see self::roleOf()} — see that method for why a
	 * prefix is the wrong thing to reason about.
	 *
	 * @var array<int, string>
	 */
	public const COMPONENT_PREFIXES = ['--utrecht-', '--ams-', '--denhaag-', '--conduction-'];

	/**
	 * Role heads that mean "a raw design-token VALUE", not a component part.
	 *
	 * Everything else is a component token. Deliberately a short list of value
	 * vocabularies rather than a long list of component names: a design system
	 * invents new components constantly and names them freely, but the handful
	 * of scales a theme is built from (`color-*`, `size-*`, `font-size-*`, …)
	 * barely changes. Guessing wrong in this direction is also the safe way
	 * round — an unrecognised name is treated as a component and kept verbatim,
	 * which loses nothing, where treating a component as palette renames it out
	 * of the vocabulary that reads it.
	 *
	 * @var array<int, string>
	 */
	private const PALETTE_ROLE_HEADS = [
		'color',
		'colour',
		'size',
		'sizing',
		'font-size',
		'font-weight',
		'font-family',
		'typography',
		'space',
		'spacing',
		'radius',
		'shadow',
		'breakpoint',
		'opacity',
		'z-index',
		'border-radius',
		'line-height',
	];

	/**
	 * Maximum `var()` indirections followed before a chain is abandoned.
	 *
	 * @var int
	 */
	private const MAX_VAR_DEPTH = 10;

	/**
	 * Maximum darkening steps the contrast guard may take (spec: 10).
	 *
	 * @var int
	 */
	private const MAX_CONTRAST_STEPS = 10;

	/**
	 * The decoded mapping table, loaded once per request.
	 *
	 * @var array<string, mixed>|null
	 */
	private ?array $table = null;

	/**
	 * SHA-256 of the mapping table file, for the provenance block.
	 *
	 * @var string|null
	 */
	private ?string $tableHash = null;

	/**
	 * The `--nldesign-*` names the app itself declares or reads, used to tell a
	 * real semantic token from a raw upstream palette step that was dumped
	 * under the app's prefix.
	 *
	 * @var array<string, bool>|null
	 */
	private ?array $knownVocabulary = null;

	/**
	 * DTCG `$deprecated` import warnings from the last input-B conversion.
	 *
	 * Kept apart from the conversion report on purpose: an import warning is a
	 * statement about the SOURCE document (a token its author marked
	 * deprecated), not about what this app did with it, and the panel renders
	 * the two in different places.
	 *
	 * @var array<int, array{path: string, message: string|null}>
	 */
	private array $importWarnings = [];

	/**
	 * DTCG hard mapping errors from the last input-B conversion.
	 *
	 * @var array<int, array{path: string, reason: string, detail?: string}>
	 */
	private array $mapperErrors = [];

	/**
	 * Constructor.
	 *
	 * @param IAppManager        $appManager The app manager, for locating the mapping table and the vocabulary stylesheets.
	 * @param CssParserService   $cssParser  Declaration parsing (shared with every other CSS path in the app).
	 * @param ContrastService    $contrast   WCAG ratio maths for the contrast guard.
	 * @param DesignTokensMapper $dtcgMapper The existing DTCG mapper, which owns input B.
	 * @param FontService        $fonts      Bundled/uploaded font lookup for the `fontAvailable` guard.
	 * @param LoggerInterface    $logger     Logger for a malformed mapping table.
	 */
	public function __construct(
		private readonly IAppManager $appManager,
		private readonly CssParserService $cssParser,
		private readonly ContrastService $contrast,
		private readonly DesignTokensMapper $dtcgMapper,
		private readonly FontService $fonts,
		private readonly LoggerInterface $logger,
	) {
	}//end __construct()

	/**
	 * Convert a design-system theme into a Nextcloud token set.
	 *
	 * @param string      $content     The raw pasted or uploaded content.
	 * @param string      $slug        The token set slug, which is also the brand prefix (`--{slug}-*`).
	 * @param string      $displayName The human-readable set name for the manifest entry.
	 * @param string|null $sourceName  Optional source label (file name or package) for the provenance block.
	 * @param string|null $assetName   Base name for an extracted logo, WITHOUT extension. Defaults to
	 *                                 the slug; the admin upload path passes `custom-{slug}` so an
	 *                                 uploaded theme can never overwrite a shipped `img/logos/{slug}.svg`.
	 *
	 * @return array{
	 *     css: string,
	 *     manifestEntry: array<string, mixed>,
	 *     report: array<int, ReportEntry>,
	 *     inputKind: string,
	 *     counts: array<string, int>,
	 *     logoAsset: array{path: string, contents: string}|null,
	 *     importWarnings: array<int, array{path: string, message: string|null}>,
	 *     errors: array<int, array{path: string, reason: string, detail?: string}>
	 * }
	 *
	 * @throws RuntimeException When the content matches none of the four accepted shapes (code 422).
	 *
	 * @spec openspec/changes/nlds-theme-converter/specs/token-set-converter/spec.md
	 */
	public function convert(
		string $content,
		string $slug,
		string $displayName,
		?string $sourceName = null,
		?string $assetName = null,
	): array {
		$report = [];
		$this->importWarnings = [];
		$this->mapperErrors = [];

		$inputKind = $this->detectInput(content: $content);
		$sourceVersion = null;

		if ($inputKind === 'B' || $inputKind === 'C') {
			$decoded = json_decode($content, true);
			$declarations = $this->declarationsFromJson(
				decoded: $decoded,
				kind: $inputKind,
				slug: $slug,
				version: $sourceVersion,
				report: $report
			);
		} else {
			$declarations = $this->parseCssBlocks(content: $content, report: $report);
		}

		if (empty($declarations) === true) {
			throw new RuntimeException(
				'No custom properties were found. Paste a built theme CSS (a class-scoped block of'
				. ' --custom-properties), a W3C Design Tokens JSON document, a Style Dictionary'
				. ' tokens.json, or an existing :root token set.',
				422
			);
		}

		// A value pointing at a remote host never reaches the emitted file: a
		// token set is served to every anonymous visitor, so an external url()
		// would be a third-party request on the login page.
		$declarations = $this->stripExternalUrls(declarations: $declarations, report: $report);

		// Resolve `var()` chains to literals so the file stands on its own. A
		// token set is also served on the login page and in e-mails, where the
		// source theme's own variables do not exist.
		$declarations = $this->resolveVars(declarations: $declarations, report: $report);

		// Lift the theme's logo out of the stylesheet and into a file, BEFORE
		// the sections are built: Nextcloud's core theming takes a logo as a
		// path on disk, never as a data URI, so this is the only step that can
		// give a converted theme a `theming.logo` at all.
		$logo = $this->extractLogo(
			declarations: $declarations,
			slug: $slug,
			assetName: ($assetName ?? $slug),
			report: $report
		);

		if ($logo !== null) {
			// The source declaration is re-emitted from `$logo['css']` after the
			// rules run; every other slot carrying the same artwork points at it
			// instead of repeating the payload (the shape opencatalogi.css uses).
			unset($declarations[$logo['source']]);
			foreach ($logo['aliases'] as $alias) {
				$declarations[$alias] = 'var(--nldesign-logo-url)';
			}
		}

		// Split the input into the three emitted sections.
		$sections = $this->classify(declarations: $declarations, slug: $slug, inputKind: $inputKind, report: $report);

		// The semantic layer, from the table. `existing` carries input D's
		// hand-authored values, which win over anything the rules derive.
		$semantic = $this->runRules(
			declarations: $declarations,
			existing: $sections['semantic'],
			slug: $slug,
			manifest: $manifest,
			report: $report
		);

		if ($logo !== null) {
			$semantic['--nldesign-logo-url'] = $logo['css'];
		}

		$counts = $this->countActions(report: $report);

		$css = $this->buildCss(
			palette: $sections['palette'],
			component: $sections['component'],
			semantic: $semantic,
			slug: $slug,
			inputKind: $inputKind,
			sourceName: $sourceName,
			sourceVersion: $sourceVersion,
			counts: $counts
		);

		// Only set when the logo was DECODED out of the theme, so the caller has
		// bytes to write. A theme that already pointed at a file on disk yields
		// a `theming.logo` with no asset to create.
		$logoAsset = null;
		if ($logo !== null && $logo['contents'] !== null) {
			$logoAsset = ['path' => $logo['path'], 'contents' => $logo['contents']];
		}

		return [
			'css' => $css,
			'manifestEntry' => $this->buildManifestEntry(
				slug: $slug,
				displayName: $displayName,
				semantic: $semantic,
				manifest: ($manifest ?? []),
				sourceName: $sourceName,
				sourceVersion: $sourceVersion,
				logo: $logo
			),
			'report' => $report,
			'inputKind' => $inputKind,
			'counts' => $counts,
			'logoAsset' => $logoAsset,
			'importWarnings' => $this->importWarnings,
			'errors' => $this->mapperErrors,
		];
	}//end convert()

	/**
	 * The reason-code copy from the mapping table, for rendering a report.
	 *
	 * @return array<string, string> Reason code => one-sentence explanation.
	 */
	public function getReasons(): array {
		$table = $this->table();

		if (is_array($table['reasons'] ?? null) === true) {
			return $table['reasons'];
		}

		return [];
	}//end getReasons()

	/**
	 * Load and cache the mapping table.
	 *
	 * @return array<string, mixed> The decoded table.
	 *
	 * @throws RuntimeException When the table is missing or unreadable (code 500).
	 */
	private function table(): array {
		if ($this->table !== null) {
			return $this->table;
		}

		$path = $this->appManager->getAppPath('thematiq') . '/scripts/mapping/nlds-to-nextcloud.json';
		$raw = false;
		if (is_file($path) === true) {
			$raw = file_get_contents($path);
		}

		if ($raw === false) {
			$this->logger->error('Thematiq: mapping table not readable at ' . $path);

			throw new RuntimeException('The token conversion mapping table is missing from this installation.', 500);
		}

		$decoded = json_decode($raw, true);
		if (is_array($decoded) === false || is_array($decoded['rules'] ?? null) === false) {
			$this->logger->error('Thematiq: mapping table at ' . $path . ' is not a valid rule list.');

			throw new RuntimeException('The token conversion mapping table is malformed.', 500);
		}

		$this->tableHash = hash(algo: 'sha256', data: $raw);
		$this->table = $decoded;

		return $this->table;
	}//end table()

	/**
	 * Determine which of the four accepted shapes the content is.
	 *
	 * Detection is by content only. The order is fixed so the same paste always
	 * lands in the same branch: JSON first (a DTCG document and a Style
	 * Dictionary tree are told apart by the presence of a `$value` leaf), then
	 * CSS, where a `:root` selector carrying `--nldesign-*` names is an existing
	 * token set (D) and anything else with custom properties is a built theme (A).
	 *
	 * @param string $content The raw content.
	 *
	 * @return string One of `A`, `B`, `C`, `D`.
	 *
	 * @throws RuntimeException When the content matches none of the shapes (code 422).
	 */
	private function detectInput(string $content): string {
		$trimmed = trim($content);

		if ($trimmed !== '' && ($trimmed[0] === '{' || $trimmed[0] === '[')) {
			$decoded = json_decode($trimmed, true);
			if (is_array($decoded) === true) {
				if ($this->hasDtcgLeaf(node: $decoded) === true) {
					return 'B';
				}

				return 'C';
			}
		}

		$stripped = (string)preg_replace('#/\*.*?\*/#s', '', $content);
		if (preg_match('/--[\w-]+\s*:/', $stripped) !== 1) {
			throw new RuntimeException(
				'The content is not a theme this app can convert. Accepted: built theme CSS with a'
				. ' class-scoped block of --custom-properties, a W3C Design Tokens JSON document, a'
				. ' Style Dictionary tokens.json, or an existing :root token set.',
				422
			);
		}

		if (preg_match('/:root\s*\{/i', $stripped) === 1 && preg_match('/--nldesign-/', $stripped) === 1) {
			return 'D';
		}

		return 'A';
	}//end detectInput()

	/**
	 * Whether any node in a decoded JSON tree is a DTCG leaf (`$value`).
	 *
	 * @param mixed $node  The current node.
	 * @param int   $depth Current recursion depth.
	 *
	 * @return bool True when a `$value` key is present anywhere.
	 */
	private function hasDtcgLeaf(mixed $node, int $depth = 0): bool {
		if (is_array($node) === false || $depth > 12) {
			return false;
		}

		if (array_key_exists('$value', $node) === true) {
			return true;
		}

		foreach ($node as $child) {
			if ($this->hasDtcgLeaf(node: $child, depth: ($depth + 1)) === true) {
				return true;
			}
		}

		return false;
	}//end hasDtcgLeaf()

	/**
	 * Collect declarations from every selector block in a CSS input.
	 *
	 * At-rules are reported and skipped rather than descended into: a token set
	 * is one flat block of values, so a `@media` branch has nowhere to go. Later
	 * blocks win over earlier ones, which is what the cascade would do anyway.
	 *
	 * @param string                  $content The raw CSS.
	 * @param array<int, ReportEntry> $report  The report, appended to by reference.
	 *
	 * @return array<string, string> Declaration name => raw value.
	 */
	private function parseCssBlocks(string $content, array &$report): array {
		$stripped = (string)preg_replace('#/\*.*?\*/#s', '', $content);

		if (preg_match_all('/@([a-z-]+)[^{;]*/i', $stripped, $atRules) > 0) {
			foreach (array_unique($atRules[0]) as $atRule) {
				$report[] = [
					'source' => trim($atRule),
					'target' => '',
					'action' => 'skipped',
					'reason' => 'at-rule-not-converted',
					'value' => null,
				];
			}
		}

		// Drop at-rule prelude+block pairs so their declarations are not read.
		$stripped = (string)preg_replace('/@[a-z-]+[^{;]*\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}/is', '', $stripped);
		$stripped = (string)preg_replace('/@[a-z-]+[^;{]*;/i', '', $stripped);

		$declarations = [];
		if (preg_match_all('/([^{}]+)\{([^{}]*)\}/s', $stripped, $blocks, PREG_SET_ORDER) > 0) {
			foreach ($blocks as $block) {
				$parsed = $this->cssParser->parseDeclarations(content: $block[2]);
				if ($parsed !== null) {
					$declarations = array_merge($declarations, $parsed);
				}
			}
		}

		return $declarations;
	}//end parseCssBlocks()

	/**
	 * Collect declarations from a JSON input.
	 *
	 * Input B is handed to `DesignTokensMapper` verbatim — it owns DTCG alias
	 * resolution, `$type` dispatch and the suffix table, and duplicating any of
	 * that here is exactly the drift this change exists to prevent. Input C is a
	 * plain Style Dictionary tree, whose leaves are `value` (not `$value`) and
	 * whose dotted path becomes the token name.
	 *
	 * @param array<mixed>            $decoded The decoded JSON.
	 * @param string                  $kind    `B` or `C`.
	 * @param string                  $slug    The brand prefix for input C names.
	 * @param string|null             $version Set to the declared package version when the input carries one.
	 * @param array<int, ReportEntry> $report  The report, appended to by reference.
	 *
	 * @return array<string, string> Declaration name => value.
	 */
	private function declarationsFromJson(array $decoded, string $kind, string $slug, ?string &$version, array &$report): array {
		if ($kind === 'B') {
			$mapped = $this->dtcgMapper->map(document: $decoded);
			$version = $mapped['packageVersion'];
			$this->importWarnings = $mapped['warnings'];
			$this->mapperErrors = $mapped['errors'];

			foreach ($mapped['skipped'] as $skip) {
				$report[] = [
					'source' => (string)($skip['path'] ?? ''),
					'target' => '',
					'action' => 'skipped',
					'reason' => 'unmapped',
					'value' => null,
				];
			}

			return $mapped['declarations'];
		}

		$declarations = [];
		$this->collectStyleDictionaryLeaves(node: $decoded, path: [], slug: $slug, declarations: $declarations);

		return $declarations;
	}//end declarationsFromJson()

	/**
	 * Flatten a Style Dictionary tree into custom-property declarations.
	 *
	 * A leaf is a node carrying a `value` key. The dotted path becomes the token
	 * name: a path that already begins with a known component prefix keeps it
	 * (`utrecht.button.…` becomes `--utrecht-button-…`), everything else is
	 * namespaced under the brand slug, which is the whole point — a raw palette
	 * step must never end up under the app's own `--nldesign-` vocabulary.
	 *
	 * @param mixed                 $node         The current node.
	 * @param array<int, string>    $path         The path walked so far.
	 * @param string                $slug         The brand prefix.
	 * @param array<string, string> $declarations Collected declarations, by reference.
	 * @param int                   $depth        Current recursion depth.
	 *
	 * @return void
	 */
	private function collectStyleDictionaryLeaves(mixed $node, array $path, string $slug, array &$declarations, int $depth = 0): void {
		if (is_array($node) === false || $depth > 12) {
			return;
		}

		if (array_key_exists('value', $node) === true && is_array($node['value']) === false) {
			$segments = array_map(
				static fn (string $segment): string => strtolower((string)preg_replace('/[^A-Za-z0-9]+/', '-', $segment)),
				$path
			);
			$joined = trim(implode('-', array_filter($segments)), '-');
			if ($joined === '') {
				return;
			}

			$prefixed = '--' . $slug . '-' . $joined;
			foreach (self::COMPONENT_PREFIXES as $prefix) {
				$bare = trim($prefix, '-');
				if (str_starts_with($joined, $bare . '-') === true) {
					$prefixed = '--' . $joined;
					break;
				}
			}

			$declarations[$prefixed] = trim((string)$node['value']);

			return;
		}

		foreach ($node as $key => $child) {
			if (is_string($key) === false || str_starts_with($key, '$') === true) {
				continue;
			}

			$this->collectStyleDictionaryLeaves(
				node: $child,
				path: array_merge($path, [$key]),
				slug: $slug,
				declarations: $declarations,
				depth: ($depth + 1)
			);
		}
	}//end collectStyleDictionaryLeaves()

	/**
	 * Drop declarations whose value points at a remote host.
	 *
	 * Existing policy from the wave-3 and wave-5 security fixes: Thematiq serves
	 * only local assets, and a token set reaches every anonymous visitor.
	 *
	 * @param array<string, string>   $declarations The parsed declarations.
	 * @param array<int, ReportEntry> $report       The report, appended to by reference.
	 *
	 * @return array<string, string> The declarations without external references.
	 */
	private function stripExternalUrls(array $declarations, array &$report): array {
		$kept = [];

		foreach ($declarations as $name => $value) {
			if (preg_match('#url\(\s*[\'"]?(?:https?:)?//#i', $value) === 1) {
				$report[] = [
					'source' => $name,
					'target' => '',
					'action' => 'skipped',
					'reason' => 'external-url-blocked',
					'value' => null,
				];
				continue;
			}

			$kept[$name] = $value;
		}

		return $kept;
	}//end stripExternalUrls()

	/**
	 * Resolve `var()` chains against the input's own declarations.
	 *
	 * Depth-limited and cycle-guarded. A reference the input does not define is
	 * NOT emitted: the value would resolve to nothing on the login page and in
	 * e-mails, where the source theme's stylesheet is not loaded.
	 *
	 * @param array<string, string>   $declarations The parsed declarations.
	 * @param array<int, ReportEntry> $report       The report, appended to by reference.
	 *
	 * @return array<string, string> Declarations with every value a literal.
	 */
	private function resolveVars(array $declarations, array &$report): array {
		$resolved = [];

		foreach ($declarations as $name => $value) {
			$literal = $this->resolveValue(value: $value, declarations: $declarations, seen: [$name => true], depth: 0);

			if ($literal === null) {
				$report[] = [
					'source' => $name,
					'target' => '',
					'action' => 'skipped',
					'reason' => 'unresolved-var',
					'value' => $value,
				];
				continue;
			}

			$resolved[$name] = $literal;
		}

		return $resolved;
	}//end resolveVars()

	/**
	 * Resolve one value's `var()` references to a literal.
	 *
	 * @param string                $value        The raw value.
	 * @param array<string, string> $declarations The full declaration map.
	 * @param array<string, bool>   $seen         Names already on this chain (cycle guard).
	 * @param int                   $depth        Current depth.
	 *
	 * @return string|null The literal value, or null when a reference cannot be resolved.
	 */
	private function resolveValue(string $value, array $declarations, array $seen, int $depth): ?string {
		if (str_contains($value, 'var(') === false) {
			return trim($value);
		}

		if ($depth >= self::MAX_VAR_DEPTH) {
			return null;
		}

		$failed = false;
		$result = preg_replace_callback(
			'/var\(\s*(--[\w-]+)\s*(?:,\s*([^()]*(?:\([^()]*\)[^()]*)*))?\)/',
			function (array $match) use ($declarations, $seen, $depth, &$failed): string {
				$reference = $match[1];
				$fallback = ($match[2] ?? null);

				if (isset($seen[$reference]) === false && array_key_exists($reference, $declarations) === true) {
					$inner = $this->resolveValue(
						value: $declarations[$reference],
						declarations: $declarations,
						seen: array_merge($seen, [$reference => true]),
						depth: ($depth + 1)
					);

					if ($inner !== null) {
						return $inner;
					}
				}

				if ($fallback !== null && trim($fallback) !== '') {
					$inner = $this->resolveValue(
						value: trim($fallback),
						declarations: $declarations,
						seen: $seen,
						depth: ($depth + 1)
					);

					if ($inner !== null) {
						return $inner;
					}
				}

				$failed = true;

				return '';
			},
			$value
		);

		if ($failed === true || $result === null) {
			return null;
		}

		return trim($result);
	}//end resolveValue()

	/**
	 * Lift the theme's logo out of the declarations and into a writable asset.
	 *
	 * A theme carries its wordmark inline — `url("data:image/svg+xml;base64,…")`
	 * on a logo token — and Nextcloud's core theming cannot use that: the
	 * theming-sync spec's `theming.logo` is a path under `img/logos/` that must
	 * exist on disk, because `ImageManager::updateImage()` copies a FILE. So the
	 * payload is decoded here, handed back for the caller to write, and the
	 * stylesheet is left pointing at the written file instead.
	 *
	 * A theme that already points at a local path (re-converting an existing
	 * token set) is recognised too: no bytes, but the path still reaches the
	 * manifest so the set gains the `theming.logo` it was missing.
	 *
	 * @param array<string, string>   $declarations The resolved declarations.
	 * @param string                  $slug         The brand slug, substituted for `{p}`.
	 * @param string                  $assetName    Base name for the written file, without extension.
	 * @param array<int, ReportEntry> $report       The report, appended to by reference.
	 *
	 * @return array{source: string, aliases: array<int, string>, path: string, css: string, contents: string|null}|null
	 *         The extracted logo, or null when the theme declares none.
	 *
	 * @spec openspec/specs/theming-sync/spec.md
	 * @spec openspec/changes/nlds-theme-converter/specs/token-set-converter/spec.md
	 */
	private function extractLogo(array $declarations, string $slug, string $assetName, array &$report): ?array {
		$spec = ($this->table()['logo'] ?? null);
		if (is_array($spec) === false) {
			return null;
		}

		foreach ($this->logoCandidates(declarations: $declarations, slug: $slug, spec: $spec) as $name) {
			$value = $declarations[$name];

			$target = null;
			if (preg_match('/url\(\s*([\'"]?)(.*?)\1\s*\)/is', $value, $matches) === 1) {
				$target = trim($matches[2]);
			}

			if ($target === null || $target === '' || strcasecmp($target, 'none') === 0) {
				continue;
			}

			$decoded = $this->decodeLogoUri(uri: $target, spec: $spec);

			if ($decoded === null) {
				// A local path the theme already resolved: keep it, no bytes.
				$path = $this->localLogoPath(target: $target, spec: $spec);
				if ($path === null) {
					$report[] = [
						'source' => $name,
						'target' => '--nldesign-logo-url',
						'action' => 'skipped',
						'reason' => 'logo-format-unsupported',
						'value' => $this->logoValueLabel(value: $value),
					];
					continue;
				}

				return [
					'source' => $name,
					'aliases' => $this->logoAliases(declarations: $declarations, source: $name, value: $value),
					'path' => $path,
					'css' => "url('../../" . $path . "')",
					'contents' => null,
				];
			}//end if

			$path = (string)$spec['directory'] . '/' . $assetName . '.' . $decoded['extension'];

			$report[] = [
				'source' => $name,
				'target' => '--nldesign-logo-url',
				'action' => 'applied',
				'reason' => (string)($spec['reason'] ?? 'logo-extracted'),
				'value' => $path,
			];

			return [
				'source' => $name,
				'aliases' => $this->logoAliases(declarations: $declarations, source: $name, value: $value),
				'path' => $path,
				'css' => "url('../../" . $path . "')",
				'contents' => $decoded['contents'],
			];
		}//end foreach

		return null;
	}//end extractLogo()

	/**
	 * The logo tokens to try, in the table's priority order.
	 *
	 * Named sources first (first match wins, exactly like a rule's sources),
	 * then anything whose ROLE says it is a logo, so a theme using a vendor
	 * prefix this app has never seen is still recognised.
	 *
	 * @param array<string, string> $declarations The resolved declarations.
	 * @param string                $slug         The brand slug, substituted for `{p}`.
	 * @param array<string, mixed>  $spec         The table's `logo` block.
	 *
	 * @return array<int, string> The candidate declaration names, in order.
	 */
	private function logoCandidates(array $declarations, string $slug, array $spec): array {
		$candidates = [];

		foreach (($spec['sources'] ?? []) as $source) {
			$name = $this->withSlug(name: (string)$source, slug: $slug);
			if (isset($declarations[$name]) === true && in_array($name, $candidates, true) === false) {
				$candidates[] = $name;
			}
		}

		$roles = array_flip(array_map('strval', ($spec['roles'] ?? [])));
		foreach (array_keys($declarations) as $name) {
			if (isset($roles[$this->roleOf(name: (string)$name)]) === true
				&& in_array($name, $candidates, true) === false
			) {
				$candidates[] = (string)$name;
			}
		}

		return $candidates;
	}//end logoCandidates()

	/**
	 * Every other declaration carrying the same artwork as the chosen source.
	 *
	 * A theme repeats its wordmark byte for byte across the header, navbar and
	 * footer slots; those slots are kept (Conduction's apps read them) but are
	 * pointed at `--nldesign-logo-url` rather than repeating the payload.
	 *
	 * @param array<string, string> $declarations The resolved declarations.
	 * @param string                $source       The chosen source declaration.
	 * @param string                $value        The chosen source's value.
	 *
	 * @return array<int, string> The alias declaration names.
	 */
	private function logoAliases(array $declarations, string $source, string $value): array {
		$aliases = [];

		foreach ($declarations as $name => $candidate) {
			if ($name !== $source && $candidate === $value) {
				$aliases[] = (string)$name;
			}
		}

		return $aliases;
	}//end logoAliases()

	/**
	 * Decode a `data:image/*` URI into raw bytes.
	 *
	 * Both encodings a theme actually uses are accepted: base64 (what Style
	 * Dictionary emits) and percent-encoded (what a hand-written SVG data URI
	 * looks like). Anything else — a bare path, a scheme, an oversized payload,
	 * an image type Nextcloud's ImageManager does not take — is not a logo this
	 * converter can store, and the caller reports it as such.
	 *
	 * @param string               $uri  The `url()` target.
	 * @param array<string, mixed> $spec The table's `logo` block.
	 *
	 * @return array{extension: string, contents: string}|null The decoded image, or null.
	 */
	private function decodeLogoUri(string $uri, array $spec): ?array {
		if (preg_match('#^data:image/([a-z0-9.+-]+)\s*(;[^,]*)?,(.*)$#is', $uri, $matches) !== 1) {
			return null;
		}

		$types = ($spec['types'] ?? []);
		$type = strtolower($matches[1]);
		if (isset($types[$type]) === false) {
			return null;
		}

		$parameters = strtolower((string)$matches[2]);
		$payload = $matches[3];

		if (str_contains($parameters, 'base64') === true) {
			$contents = base64_decode(preg_replace('/\s+/', '', $payload), true);
			if ($contents === false) {
				return null;
			}
		} else {
			$contents = rawurldecode($payload);
		}

		$maxBytes = (int)($spec['maxBytes'] ?? 262144);
		if ($contents === '' || strlen($contents) > $maxBytes) {
			return null;
		}

		return ['extension' => (string)$types[$type], 'contents' => $contents];
	}//end decodeLogoUri()

	/**
	 * Normalise a relative `url()` target to an app-root-relative asset path.
	 *
	 * Only a path that already lives in the table's logo directory is accepted:
	 * `theming.logo` is handed to `ThemingService::validateSinglePath()`, which
	 * rejects traversal and anything outside `img/logos/` and `img/backgrounds/`.
	 *
	 * @param string               $target The `url()` target.
	 * @param array<string, mixed> $spec   The table's `logo` block.
	 *
	 * @return string|null The app-relative path, or null when it is not one.
	 */
	private function localLogoPath(string $target, array $spec): ?string {
		if (preg_match('#^([a-z][a-z0-9+.-]*:|//)#i', $target) === 1) {
			return null;
		}

		$path = ltrim(preg_replace('#^(\.\./)+#', '', $target), '/');
		$directory = (string)$spec['directory'] . '/';

		if (str_starts_with($path, $directory) === false || str_contains($path, '..') === true) {
			return null;
		}

		return $path;
	}//end localLogoPath()

	/**
	 * A short, loggable stand-in for a logo value.
	 *
	 * The report is rendered in the admin panel and stored in the audit log; a
	 * rejected 40 KB data URI must not travel through either.
	 *
	 * @param string $value The declaration value.
	 *
	 * @return string The value, or a truncated marker.
	 */
	private function logoValueLabel(string $value): string {
		if (strlen($value) <= 120) {
			return $value;
		}

		return substr($value, 0, 117) . '…';
	}//end logoValueLabel()

	/**
	 * Split the resolved input into the palette, component and pre-existing
	 * semantic sections, applying the table's `never` policy on the way.
	 *
	 * @param array<string, string>   $declarations The resolved declarations.
	 * @param string                  $slug         The brand slug.
	 * @param string                  $inputKind    The detected input kind.
	 * @param array<int, ReportEntry> $report       The report, appended to by reference.
	 *
	 * @return array{palette: array<string, string>, component: array<string, string>, semantic: array<string, string>}
	 */
	private function classify(array $declarations, string $slug, string $inputKind, array &$report): array {
		$palette = [];
		$component = [];
		$semantic = [];

		$ruleTargets = $this->ruleTargets(slug: $slug);

		foreach ($declarations as $name => $value) {
			$policy = $this->policyFor(name: $name, slug: $slug);

			if ($policy !== null && ($policy['action'] ?? '') === 'skip') {
				$report[] = [
					'source' => $name,
					'target' => '',
					'action' => 'skipped',
					'reason' => (string)$policy['reason'],
					'value' => $value,
				];
				continue;
			}

			// Component or palette is decided by the ROLE, not the prefix: a
			// theme using an unknown namespace still names the job in the name,
			// and everything that is not one of the value scales is a component
			// token that has to survive verbatim.
			$role = $this->roleOf(name: $name);
			$isComponent = ($role !== '' && $this->isPaletteRole(role: $role) === false);

			if ($isComponent === true) {
				// The prefix decides only what it is CALLED. A recognised design
				// system prefix is kept as-is, because `utrecht-bridge.css` and
				// Conduction's apps read those exact names; an unfamiliar prefix
				// is moved under the set's own, keeping the role intact, so the
				// emitted file carries one namespace the validator accepts
				// instead of a vendor name nothing in this app knows.
				$emitted = $name;
				$isKnownPrefix = false;
				foreach (self::COMPONENT_PREFIXES as $prefix) {
					if (str_starts_with($name, $prefix) === true) {
						$isKnownPrefix = true;
						break;
					}
				}

				if ($isKnownPrefix === false) {
					$emitted = '--' . $slug . '-' . $role;
				}

				$component[$emitted] = $value;

				if ($policy !== null && ($policy['action'] ?? '') === 'keep') {
					$report[] = [
						'source' => $name,
						'target' => $emitted,
						'action' => 'kept',
						'reason' => (string)$policy['reason'],
						'value' => $value,
					];
					continue;
				}

				// A component token a rule consumes is reported by runRules() as
				// `applied`; one no rule names is still emitted for the NLDS
				// components that read it, and named here so the mapping table
				// can be extended. Checked by role as well as by name, because
				// that is how runRules() resolves its sources.
				if (isset($ruleTargets['sources'][$name]) === false
					&& isset($ruleTargets['roles'][$role]) === false
				) {
					$report[] = [
						'source' => $name,
						'target' => $emitted,
						'action' => 'kept',
						'reason' => 'unmapped',
						'value' => $value,
					];
				}

				continue;
			}//end if

			if (str_starts_with($name, '--nldesign-') === true) {
				// A real semantic token: input D's hand-authored value, which
				// add-only re-conversion must not overwrite.
				if (isset($this->vocabulary()[$name]) === true || isset($ruleTargets['targets'][$name]) === true) {
					$semantic[$name] = $value;
					$report[] = [
						'source' => $name,
						'target' => $name,
						'action' => 'kept',
						'reason' => 'kept-existing-value',
						'value' => $value,
					];
					continue;
				}

				// A raw upstream palette step dumped under the app's prefix,
				// where it masquerades as app vocabulary while nothing can read
				// it. Moved to the brand prefix, where the semantic layer can.
				$renamed = '--' . $slug . '-' . substr($name, strlen('--nldesign-'));
				$palette[$renamed] = $value;
				$report[] = [
					'source' => $name,
					'target' => $renamed,
					'action' => 'adapted',
					'reason' => 'palette-reprefixed',
					'value' => $value,
				];
				continue;
			}//end if

			// Everything else is brand palette. Names already under the slug keep
			// their name; a theme using its own prefix is re-namespaced so one
			// set never carries two vocabularies.
			$renamed = $name;
			if (str_starts_with($name, '--' . $slug . '-') === false) {
				$renamed = '--' . $slug . '-' . $role;
			}

			$palette[$renamed] = $value;

			if ($policy !== null && ($policy['action'] ?? '') === 'keep') {
				$report[] = [
					'source' => $name,
					'target' => $renamed,
					'action' => 'kept',
					'reason' => (string)$policy['reason'],
					'value' => $value,
				];
				continue;
			}

			if (isset($ruleTargets['sources'][$name]) === false) {
				$report[] = [
					'source' => $name,
					'target' => $renamed,
					'action' => 'kept',
					'reason' => 'unmapped',
					'value' => $value,
				];
			}
		}//end foreach

		return [
			'palette' => $palette,
			'component' => $component,
			'semantic' => $semantic,
		];
	}//end classify()

	/**
	 * Every rule target and every named source, for O(1) lookups.
	 *
	 * @param string $slug The brand slug, substituted for `{p}`.
	 *
	 * @return array{targets: array<string, bool>, sources: array<string, bool>, roles: array<string, bool>}
	 */
	private function ruleTargets(string $slug): array {
		$targets = [];
		$sources = [];
		$roles = [];

		foreach ($this->table()['rules'] as $rule) {
			$target = (string)($rule['target'] ?? '');
			if ($target !== '' && str_starts_with($target, 'manifest:') === false) {
				$targets[$target] = true;
			}

			foreach (($rule['sources'] ?? []) as $source) {
				$concrete = $this->withSlug(name: (string)$source, slug: $slug);
				$sources[$concrete] = true;

				$role = $this->roleOf(name: $concrete);
				if ($role !== '') {
					$roles[$role] = true;
				}
			}
		}//end foreach

		return ['targets' => $targets, 'sources' => $sources, 'roles' => $roles];
	}//end ruleTargets()

	/**
	 * The `--nldesign-*` names the app declares a default for or reads.
	 *
	 * Read from the two stylesheets that define the vocabulary, so this service
	 * and `TokenSetVocabularyAuditService` agree on what "app vocabulary" means
	 * without either hard-coding a list that can rot.
	 *
	 * @return array<string, bool> Name => true.
	 */
	private function vocabulary(): array {
		if ($this->knownVocabulary !== null) {
			return $this->knownVocabulary;
		}

		$appPath = $this->appManager->getAppPath('thematiq');
		$names = [];

		foreach (['/css/systems/nldesign/defaults.css', '/css/systems/nldesign/utrecht-bridge.css'] as $relative) {
			$path = $appPath . $relative;
			if (is_file($path) === false) {
				continue;
			}

			$css = (string)file_get_contents($path);
			if (preg_match_all('/(--nldesign-[\w-]+)/', $css, $matches) > 0) {
				foreach ($matches[1] as $name) {
					$names[$name] = true;
				}
			}
		}

		$this->knownVocabulary = $names;

		return $this->knownVocabulary;
	}//end vocabulary()

	/**
	 * The ROLE of a token name: everything after its vendor prefix.
	 *
	 * `--utrecht-button-border-radius`, `--conduction-button-border-radius` and
	 * `--gemeente-xyz-button-border-radius` all have the role
	 * `button-border-radius`, and that is the only part that says what the token
	 * DOES. Matching on the prefix instead is wrong twice over: a theme may use
	 * a prefix this app has never heard of (a municipality's own design system,
	 * a white-label build), and the same prefix carries both palette and
	 * component tokens. An NL Design System theme names the job in the name —
	 * `-border-radius`, `-background-color`, `-logo-inline-size`,
	 * `-padding-block-start` — so the role is what the policy and the rule
	 * sources are matched against.
	 *
	 * Only the first segment is stripped, because that is the vendor namespace;
	 * `--openwoo-color-green-33` has the role `color-green-33`, not `green-33`.
	 *
	 * @param string $name The declaration name.
	 *
	 * @return string The role, or the bare name when it has no prefix segment.
	 */
	private function roleOf(string $name): string {
		$bare = ltrim($name, '-');
		$separator = strpos($bare, '-');

		if ($separator === false) {
			return $bare;
		}

		return substr($bare, ($separator + 1));
	}//end roleOf()

	/**
	 * Whether a role names a raw palette/scale value rather than a component part.
	 *
	 * @param string $role The role, from {@see self::roleOf()}.
	 *
	 * @return bool True when the token is brand palette.
	 */
	private function isPaletteRole(string $role): bool {
		foreach (self::PALETTE_ROLE_HEADS as $head) {
			if ($role === $head || str_starts_with($role, $head . '-') === true) {
				return true;
			}
		}

		return false;
	}//end isPaletteRole()

	/**
	 * Index the input by role, so a rule source matches whatever prefix the
	 * theme happens to use.
	 *
	 * A known component prefix wins over an unknown one for the same role, so a
	 * theme that declares both `--utrecht-button-…` and its own
	 * `--brand-button-…` resolves to the standard one.
	 *
	 * @param array<string, string> $declarations The resolved input.
	 *
	 * @return array<string, string> Role => value.
	 */
	private function indexByRole(array $declarations): array {
		$byRole = [];
		$fromKnownPrefix = [];

		foreach ($declarations as $name => $value) {
			$role = $this->roleOf(name: $name);
			if ($role === '') {
				continue;
			}

			$isKnown = false;
			foreach (self::COMPONENT_PREFIXES as $prefix) {
				if (str_starts_with($name, $prefix) === true) {
					$isKnown = true;
					break;
				}
			}

			if (isset($byRole[$role]) === true && ($isKnown === false || isset($fromKnownPrefix[$role]) === true)) {
				continue;
			}

			$byRole[$role] = $value;
			if ($isKnown === true) {
				$fromKnownPrefix[$role] = true;
			}
		}//end foreach

		return $byRole;
	}//end indexByRole()

	/**
	 * Substitute the brand-prefix placeholder in a table name.
	 *
	 * @param string $name The table name, possibly containing `{p}`.
	 * @param string $slug The brand slug.
	 *
	 * @return string The concrete name.
	 */
	private function withSlug(string $name, string $slug): string {
		return str_replace('{p}', $slug, $name);
	}//end withSlug()

	/**
	 * The `never` policy entry matching a source name, if any.
	 *
	 * @param string $name The source declaration name.
	 * @param string $slug The brand slug.
	 *
	 * @return array<string, mixed>|null The matching policy entry, or null.
	 */
	private function policyFor(string $name, string $slug): ?array {
		$role = $this->roleOf(name: $name);

		foreach (($this->table()['never'] ?? []) as $entry) {
			$pattern = $this->withSlug(name: (string)($entry['match'] ?? ''), slug: $slug);
			if ($pattern === '') {
				continue;
			}

			$regex = '/^' . str_replace('\*', '.*', preg_quote($pattern, '/')) . '$/';
			if (preg_match($regex, $name) === 1) {
				return $entry;
			}

			// Matched again on the ROLE, with the pattern's own prefix stripped,
			// so a policy written as `--utrecht-*-border-width` also catches
			// `--brand-button-border-width` from a theme this app has never
			// seen. The policy is about what the token does, not who named it.
			$rolePattern = $this->roleOf(name: $pattern);
			if ($rolePattern === '' || $rolePattern === $pattern) {
				continue;
			}

			$roleRegex = '/^' . str_replace('\*', '.*', preg_quote($rolePattern, '/')) . '$/';
			if (preg_match($roleRegex, $role) === 1) {
				return $entry;
			}
		}//end foreach

		return null;
	}//end policyFor()

	/**
	 * Produce the `--nldesign-*` semantic layer from the table.
	 *
	 * Rules are walked in order, because later ones derive from earlier targets
	 * (`-primary-light-hover` mixes the already-computed `-primary-light`). For
	 * each rule the first source the input declares wins; when none does, the
	 * fallback runs and the entry is `adapted`, never `applied` — an admin has
	 * to be able to tell the theme's own value from one this app invented.
	 *
	 * @param array<string, string>      $declarations The resolved input.
	 * @param array<string, string>      $existing     Values the input already declared (input D wins).
	 * @param string                     $slug         The brand slug.
	 * @param array<string, string>|null $manifest     Manifest targets, written by reference.
	 * @param array<int, ReportEntry>    $report       The report, appended to by reference.
	 *
	 * @return array<string, string> The semantic layer.
	 */
	private function runRules(array $declarations, array $existing, string $slug, ?array &$manifest, array &$report): array {
		$semantic = $existing;
		$manifest = [];

		foreach ($this->table()['rules'] as $rule) {
			$target = (string)($rule['target'] ?? '');
			if ($target === '') {
				continue;
			}

			$isManifest = str_starts_with($target, 'manifest:');

			// Add-only: a value the set already carries is never recomputed.
			if ($isManifest === false && array_key_exists($target, $semantic) === true) {
				continue;
			}

			if (isset($rule['when']) === true && $this->whenSatisfied(when: $rule['when'], semantic: $semantic) === false) {
				continue;
			}

			$value = null;
			$action = 'applied';
			$reason = ($rule['reason'] ?? null);
			$sourceName = '';

			$byRole = $this->indexByRole(declarations: $declarations);

			foreach (($rule['sources'] ?? []) as $candidate) {
				$concrete = $this->withSlug(name: (string)$candidate, slug: $slug);

				if (array_key_exists($concrete, $declarations) === true) {
					$value = $declarations[$concrete];
					$sourceName = $concrete;
					break;
				}

				// The table names its sources with the prefixes the reference
				// design systems use, but the ROLE is what identifies the token.
				// A theme that calls its primary action background
				// `--brand-button-primary-action-background-color` still matches
				// the `--utrecht-…` source, because the role is identical.
				$role = $this->roleOf(name: $concrete);
				if ($role !== '' && array_key_exists($role, $byRole) === true) {
					$value = $byRole[$role];
					$sourceName = $role . ' (by role)';
					break;
				}
			}//end foreach

			if ($value === null) {
				$derived = $this->applyFallback(
					fallback: ($rule['fallback'] ?? null),
					semantic: $semantic,
					declarations: $declarations,
					slug: $slug
				);

				if ($derived === null) {
					continue;
				}

				$value = $derived['value'];
				$action = 'adapted';
				$sourceName = $derived['source'];
				if ($reason === null) {
					$reason = $derived['reason'];
				}
			}

			if (isset($rule['transform']) === true && $sourceName !== '' && $action === 'applied') {
				$value = $this->transform(
					kind: (string)$rule['transform'],
					value: $value,
					args: ($rule['args'] ?? []),
					semantic: $semantic
				);
			}

			$entry = [
				'source' => $sourceName,
				'target' => $target,
				'action' => $action,
				'reason' => $reason,
				'value' => $value,
			];

			if (isset($rule['guard']) === true) {
				$guarded = $this->applyGuard(guard: $rule['guard'], value: $value, semantic: $semantic);
				if ($guarded['value'] !== $value) {
					$entry['original'] = $value;
					$entry['action'] = 'adapted';
					$value = $guarded['value'];
					$entry['value'] = $value;
				}

				if ($guarded['reason'] !== null) {
					$entry['reason'] = $guarded['reason'];
				}
			}

			if ($isManifest === true) {
				$manifest[substr($target, strlen('manifest:'))] = $value;
			} else {
				$semantic[$target] = $value;
			}

			$report[] = $entry;
		}//end foreach

		return $semantic;
	}//end runRules()

	/**
	 * Evaluate a rule's `when` condition.
	 *
	 * @param array<string, mixed>  $when     The condition.
	 * @param array<string, string> $semantic The semantic layer so far.
	 *
	 * @return bool True when the rule should run.
	 */
	private function whenSatisfied(array $when, array $semantic): bool {
		$kind = (string)($when['kind'] ?? '');

		if ($kind === 'sameColor') {
			$left = ($semantic[(string)($when['left'] ?? '')] ?? null);
			$right = ($semantic[(string)($when['right'] ?? '')] ?? null);
			if ($left === null || $right === null) {
				return false;
			}

			return strcasecmp(trim($left), trim($right)) === 0;
		}

		if ($kind === 'isDark') {
			$reference = ($semantic[(string)($when['ref'] ?? '')] ?? null);
			if ($reference === null) {
				return false;
			}

			$rgb = $this->contrast->parseColor(value: $reference);
			if ($rgb === null) {
				return false;
			}

			// Same threshold onColor() uses, so "dark" means one thing here.
			return $this->contrast->ratio(first: $rgb, second: [255, 255, 255]) >= 3.0;
		}

		return true;
	}//end whenSatisfied()

	/**
	 * Run a rule's fallback.
	 *
	 * @param array<string, mixed>|null $fallback     The fallback spec.
	 * @param array<string, string>     $semantic     The semantic layer so far.
	 * @param array<string, string>     $declarations The resolved input.
	 * @param string                    $slug         The brand slug.
	 *
	 * @return array{value: string, source: string, reason: string}|null The derived value, or null when it cannot be derived.
	 */
	private function applyFallback(?array $fallback, array $semantic, array $declarations, string $slug): ?array {
		if ($fallback === null) {
			return null;
		}

		$kind = (string)($fallback['kind'] ?? '');

		if ($kind === 'literal') {
			return [
				'value' => (string)($fallback['value'] ?? ''),
				'source' => '(Nextcloud default)',
				'reason' => 'nextcloud-default-used',
			];
		}

		if ($kind === 'manifest') {
			return null;
		}

		if ($kind === 'derive') {
			$from = (string)($fallback['from'] ?? '');
			$base = ($semantic[$from] ?? null);
			if ($base === null) {
				return null;
			}

			return [
				'value' => $this->transform(
					kind: (string)($fallback['transform'] ?? 'copy'),
					value: $base,
					args: ($fallback['args'] ?? []),
					semantic: $semantic
				),
				'source' => $from,
				'reason' => 'derived-from-brand',
			];
		}

		if ($kind === 'ramp') {
			$picked = $this->pickFromRamp(spec: $fallback, declarations: $declarations, slug: $slug, semantic: $semantic);
			if ($picked === null) {
				return null;
			}

			return [
				'value' => $picked,
				'source' => '(brand ramp)',
				'reason' => 'derived-from-brand',
			];
		}

		return null;
	}//end applyFallback()

	/**
	 * Pick a value out of the brand's own neutral ramp.
	 *
	 * The ramp is every near-grey colour the theme declares (channels within 12
	 * of each other). Using the brand's own greys rather than a fixed set is
	 * what keeps a converted set looking like its brand instead of like
	 * Rijkshuisstijl, which is the whole defect this converter exists to fix.
	 *
	 * @param array<string, mixed>  $spec         The ramp spec.
	 * @param array<string, string> $declarations The resolved input.
	 * @param string                $slug         The brand slug.
	 * @param array<string, string> $semantic     The semantic layer so far.
	 *
	 * @return string|null The picked colour, or null when the theme has no usable ramp.
	 */
	private function pickFromRamp(array $spec, array $declarations, string $slug, array $semantic): ?string {
		$ramp = [];
		foreach ($declarations as $value) {
			$rgb = $this->contrast->parseColor(value: $value);
			if ($rgb === null) {
				continue;
			}

			if ((max($rgb) - min($rgb)) > 12) {
				continue;
			}

			$ramp[$this->toHex(rgb: $rgb)] = $rgb;
		}

		if (empty($ramp) === true) {
			return null;
		}

		$criterion = (string)($spec['criterion'] ?? 'darkest');

		if ($criterion === 'darkest') {
			uasort($ramp, fn (array $a, array $b) => array_sum($a) <=> array_sum($b));

			return (string)array_key_first($ramp);
		}

		if ($criterion === 'nearestLuminance') {
			$targetRgb = $this->contrast->parseColor(value: (string)($spec['target'] ?? '#f2f2f2'));
			if ($targetRgb === null) {
				return null;
			}

			$best = null;
			$bestDistance = null;
			foreach ($ramp as $hex => $rgb) {
				$distance = abs(array_sum($rgb) - array_sum($targetRgb));
				if ($bestDistance === null || $distance < $bestDistance) {
					$bestDistance = $distance;
					$best = (string)$hex;
				}
			}

			return $best;
		}

		if ($criterion === 'minContrast') {
			$againstValue = ($semantic[(string)($spec['against'] ?? '')] ?? '#ffffff');
			$againstRgb = $this->contrast->parseColor(value: $againstValue);
			if ($againstRgb === null) {
				$againstRgb = [255, 255, 255];
			}

			$min = (float)($spec['min'] ?? 4.5);

			// The LIGHTEST grey that still clears the ratio: a muted role should
			// be as quiet as it is allowed to be, not as dark as possible.
			uasort($ramp, fn (array $a, array $b) => array_sum($b) <=> array_sum($a));
			foreach ($ramp as $hex => $rgb) {
				if ($this->contrast->ratio(first: $rgb, second: $againstRgb) >= $min) {
					return (string)$hex;
				}
			}

			return null;
		}//end if

		return null;
	}//end pickFromRamp()

	/**
	 * Apply one of the closed transform set.
	 *
	 * @param string                $kind     The transform name.
	 * @param string                $value    The input value.
	 * @param array<string, mixed>  $args     Transform arguments.
	 * @param array<string, string> $semantic The semantic layer so far (for `mix` against another token).
	 *
	 * @return string The transformed value.
	 */
	private function transform(string $kind, string $value, array $args, array $semantic): string {
		switch ($kind) {
			case 'darken':
				return $this->darken(value: $value, fraction: (float)($args['fraction'] ?? 0.1));

			case 'mix':
				$with = (string)($args['with'] ?? '#ffffff');
				if (str_starts_with($with, '--') === true) {
					$with = (string)($semantic[$with] ?? '#ffffff');
				}

				return $this->mix(value: $value, with: $with, weight: (float)($args['weight'] ?? 0.5));

			case 'rgbTriplet':
				return $this->rgbTriplet(value: $value);

			case 'alpha':
				return $this->alpha(value: $value, fraction: (float)($args['fraction'] ?? 0.5));

			case 'radiusScale':
				return $this->radiusScale(
					value: $value,
					factor: (float)($args['factor'] ?? 2),
					clampPx: (float)($args['clampPx'] ?? 16)
				);

			case 'onColor':
				return $this->onColor(
					background: $value,
					light: (string)($args['light'] ?? '#ffffff'),
					dark: (string)($args['dark'] ?? '#000000')
				);

			case 'literal':
				$template = (string)($args['template'] ?? '{value}');

				return str_replace('{value}', $value, $template);

			case 'copy':
			default:
				return $value;
		}//end switch
	}//end transform()

	/**
	 * Apply a rule's guard.
	 *
	 * @param array<string, mixed>  $guard    The guard spec.
	 * @param string                $value    The value to guard.
	 * @param array<string, string> $semantic The semantic layer so far.
	 *
	 * @return array{value: string, reason: string|null} The (possibly corrected) value and the reason when it changed.
	 */
	private function applyGuard(array $guard, string $value, array $semantic): array {
		$kind = (string)($guard['kind'] ?? '');

		if ($kind === 'fontAvailable') {
			if ($this->fontIsAvailable(stack: $value) === false) {
				return ['value' => $value, 'reason' => (string)($guard['onFail'] ?? 'font-not-bundled')];
			}

			return ['value' => $value, 'reason' => null];
		}

		if ($kind !== 'contrast') {
			return ['value' => $value, 'reason' => null];
		}

		$againstName = (string)($guard['against'] ?? '');
		$againstValue = ($semantic[$againstName] ?? null);
		if ($againstValue === null) {
			return ['value' => $value, 'reason' => null];
		}

		$rgb = $this->contrast->parseColor(value: $value);
		$againstRgb = $this->contrast->parseColor(value: $againstValue);
		if ($rgb === null || $againstRgb === null) {
			return ['value' => $value, 'reason' => null];
		}

		$min = (float)($guard['min'] ?? 4.5);
		if ($this->contrast->ratio(first: $rgb, second: $againstRgb) >= $min) {
			return ['value' => $value, 'reason' => null];
		}

		// Darken in fixed steps until the pair clears the ratio. Bounded at 10
		// steps so a pathological pair cannot spin, and the ORIGINAL is kept in
		// the report entry so the admin sees what the theme actually asked for.
		$candidate = $value;
		for ($step = 0; $step < self::MAX_CONTRAST_STEPS; $step++) {
			$candidate = $this->darken(value: $candidate, fraction: 0.1);
			$candidateRgb = $this->contrast->parseColor(value: $candidate);
			if ($candidateRgb === null) {
				break;
			}

			if ($this->contrast->ratio(first: $candidateRgb, second: $againstRgb) >= $min) {
				return ['value' => $candidate, 'reason' => (string)($guard['onFail'] ?? 'contrast-adjusted')];
			}
		}

		return ['value' => $candidate, 'reason' => (string)($guard['onFail'] ?? 'contrast-adjusted')];
	}//end applyGuard()

	/**
	 * Whether the first family of a font stack is bundled or uploaded.
	 *
	 * @param string $stack The `font-family` value.
	 *
	 * @return bool True when the family is available to the instance.
	 */
	private function fontIsAvailable(string $stack): bool {
		$first = trim(explode(',', $stack)[0], " \t\"'");
		if ($first === '') {
			return false;
		}

		$generic = ['sans-serif', 'serif', 'monospace', 'system-ui', 'cursive', 'fantasy'];
		if (in_array(strtolower($first), $generic, true) === true) {
			return true;
		}

		$slug = $this->fonts->slugify(name: $first);
		foreach ($this->fonts->list() as $font) {
			if (($font['id'] ?? '') === $slug || strcasecmp((string)($font['name'] ?? ''), $first) === 0) {
				return true;
			}
		}

		// The two families this app bundles itself.
		return in_array(strtolower($first), ['marianne', 'inter'], true);
	}//end fontIsAvailable()

	/**
	 * Darken a hex colour by a fraction. Mirrors `darkenHex()` in
	 * `js/lib/tokenTransforms.js` so both runtimes agree to the byte.
	 *
	 * @param string $value    The colour.
	 * @param float  $fraction The fraction to darken by (0 unchanged, 1 black).
	 *
	 * @return string The darkened colour, or the input when it is not a colour.
	 */
	private function darken(string $value, float $fraction): string {
		$rgb = $this->contrast->parseColor(value: $value);
		if ($rgb === null) {
			return $value;
		}

		$factor = (1 - min(1, max(0, $fraction)));

		return $this->toHex(
			rgb: [
				max(0, (int)round($rgb[0] * $factor)),
				max(0, (int)round($rgb[1] * $factor)),
				max(0, (int)round($rgb[2] * $factor)),
			]
		);
	}//end darken()

	/**
	 * Mix a colour with another by weight.
	 *
	 * `weight` is the share of the ORIGINAL retained, matching how
	 * `CommonThemeTrait` mixes an element colour with the main background, so a
	 * derived tint matches what Nextcloud would have computed itself.
	 *
	 * @param string $value  The base colour.
	 * @param string $with   The colour to mix in.
	 * @param float  $weight The share of the base retained (0-1).
	 *
	 * @return string The mixed colour, or the input when either side is not a colour.
	 */
	private function mix(string $value, string $with, float $weight): string {
		$base = $this->contrast->parseColor(value: $value);
		$other = $this->contrast->parseColor(value: $with);
		if ($base === null || $other === null) {
			return $value;
		}

		$share = min(1, max(0, $weight));

		return $this->toHex(
			rgb: [
				(int)round(($base[0] * $share) + ($other[0] * (1 - $share))),
				(int)round(($base[1] * $share) + ($other[1] * (1 - $share))),
				(int)round(($base[2] * $share) + ($other[2] * (1 - $share))),
			]
		);
	}//end mix()

	/**
	 * Render a colour as the bare `r, g, b` triplet Nextcloud's `-rgb` tokens want.
	 *
	 * @param string $value The colour.
	 *
	 * @return string The triplet, or the input when it is not a colour.
	 */
	private function rgbTriplet(string $value): string {
		$rgb = $this->contrast->parseColor(value: $value);
		if ($rgb === null) {
			return $value;
		}

		return $rgb[0] . ', ' . $rgb[1] . ', ' . $rgb[2];
	}//end rgbTriplet()

	/**
	 * Render a colour as `rgba(r, g, b, a)`.
	 *
	 * @param string $value    The colour.
	 * @param float  $fraction The alpha channel.
	 *
	 * @return string The rgba value, or the input when it is not a colour.
	 */
	private function alpha(string $value, float $fraction): string {
		$rgb = $this->contrast->parseColor(value: $value);
		if ($rgb === null) {
			return $value;
		}

		$clamped = min(1, max(0, $fraction));

		return 'rgba(' . $rgb[0] . ', ' . $rgb[1] . ', ' . $rgb[2] . ', ' . rtrim(rtrim(number_format($clamped, 2, '.', ''), '0'), '.') . ')';
	}//end alpha()

	/**
	 * Scale a px radius by a factor and clamp it.
	 *
	 * @param string $value   The radius (e.g. `4px`).
	 * @param float  $factor  The multiplier.
	 * @param float  $clampPx The maximum in px.
	 *
	 * @return string The scaled radius, or the input when it is not a px length.
	 */
	private function radiusScale(string $value, float $factor, float $clampPx): string {
		if (preg_match('/^\s*([\d.]+)px\s*$/', $value, $match) !== 1) {
			return $value;
		}

		$scaled = min($clampPx, ((float)$match[1] * $factor));

		return rtrim(rtrim(number_format($scaled, 2, '.', ''), '0'), '.') . 'px';
	}//end radiusScale()

	/**
	 * Pick the legible foreground for a background colour.
	 *
	 * @param string $background The background colour.
	 * @param string $light      The light foreground candidate.
	 * @param string $dark       The dark foreground candidate.
	 *
	 * @return string Whichever candidate contrasts better.
	 */
	private function onColor(string $background, string $light, string $dark): string {
		$rgb = $this->contrast->parseColor(value: $background);
		if ($rgb === null) {
			return $dark;
		}

		$lightRgb = ($this->contrast->parseColor(value: $light) ?? [255, 255, 255]);
		$darkRgb = ($this->contrast->parseColor(value: $dark) ?? [0, 0, 0]);

		$onLight = $this->contrast->ratio(first: $rgb, second: $lightRgb);
		$onDark = $this->contrast->ratio(first: $rgb, second: $darkRgb);

		if ($onLight >= $onDark) {
			return $light;
		}

		return $dark;
	}//end onColor()

	/**
	 * Render an RGB triple as a lower-case `#rrggbb` string.
	 *
	 * @param array{0: int, 1: int, 2: int} $rgb The colour.
	 *
	 * @return string The hex string.
	 */
	private function toHex(array $rgb): string {
		return sprintf('#%02x%02x%02x', max(0, min(255, $rgb[0])), max(0, min(255, $rgb[1])), max(0, min(255, $rgb[2])));
	}//end toHex()

	/**
	 * Tally the report by action, for the provenance block and the UI summary.
	 *
	 * @param array<int, ReportEntry> $report The report.
	 *
	 * @return array<string, int> Action => count.
	 */
	private function countActions(array $report): array {
		$counts = ['applied' => 0, 'adapted' => 0, 'skipped' => 0, 'kept' => 0];

		foreach ($report as $entry) {
			$action = (string)($entry['action'] ?? '');
			if (isset($counts[$action]) === true) {
				$counts[$action]++;
			}
		}

		return $counts;
	}//end countActions()

	/**
	 * Emit the token set file: four commented sections, one flat `:root`.
	 *
	 * The order is fixed (palette, component, semantic, provenance) so two runs
	 * of the same input diff cleanly, and every section is sorted by name for
	 * the same reason. No at-rules and exactly one selector, which is what
	 * `TokenCssShapeTest` enforces for every shipped set.
	 *
	 * @param array<string, string> $palette       The brand palette section.
	 * @param array<string, string> $component     The component layer.
	 * @param array<string, string> $semantic      The semantic layer.
	 * @param string                $slug          The brand slug.
	 * @param string                $inputKind     The detected input kind.
	 * @param string|null           $sourceName    The source label, when known.
	 * @param string|null           $sourceVersion The source package version, when declared.
	 * @param array<string, int>    $counts        The action tally.
	 *
	 * @return string The complete CSS file.
	 */
	private function buildCss(
		array $palette,
		array $component,
		array $semantic,
		string $slug,
		string $inputKind,
		?string $sourceName,
		?string $sourceVersion,
		array $counts,
	): string {
		ksort($palette);
		ksort($component);
		ksort($semantic);

		$table = $this->table();
		$lines = [];

		$lines[] = '/* GENERATED by Thematiq TokenSetConverterService — do not edit by hand.';
		$lines[] = ' * Re-run the conversion instead; hand edits are lost on the next run. */';
		$lines[] = ':root {';

		$lines[] = "\t/* 1. Brand palette — the theme's own steps, under the set's own prefix so";
		$lines[] = "\t *    they can never masquerade as app vocabulary. */";
		foreach ($palette as $name => $value) {
			$lines[] = "\t" . $name . ': ' . $value . ';';
		}

		$lines[] = '';
		$lines[] = "\t/* 2. Component layer — emitted verbatim. css/systems/nldesign/utrecht-bridge.css";
		$lines[] = "\t *    reads these into --nldesign-component-*, and Conduction's apps read them";
		$lines[] = "\t *    directly, which is why components Nextcloud lacks are kept rather than dropped. */";
		foreach ($component as $name => $value) {
			$lines[] = "\t" . $name . ': ' . $value . ';';
		}

		$lines[] = '';
		$lines[] = "\t/* 3. Semantic layer — what Nextcloud's chrome actually reads, via";
		$lines[] = "\t *    css/systems/nldesign/theme.css and overrides.css. */";
		foreach ($semantic as $name => $value) {
			$lines[] = "\t" . $name . ': ' . $value . ';';
		}

		$lines[] = '';
		$lines[] = "\t/* 4. Provenance — enough to tell two runs apart without running anything.";
		$lines[] = "\t *    input kind:      " . $inputKind . ' (' . $this->inputKindLabel(kind: $inputKind) . ')';
		$lines[] = "\t *    source:          " . ($sourceName ?? '(pasted)');
		$lines[] = "\t *    source version:  " . ($sourceVersion ?? '(not declared)');
		$lines[] = "\t *    slug:            " . $slug;
		$lines[] = "\t *    converter:       " . (string)($table['converterVersion'] ?? '0');
		$lines[] = "\t *    mapping table:   v" . (string)($table['version'] ?? '0') . ' sha256:' . substr((string)$this->tableHash, 0, 16);
		$lines[] = "\t *    applied:         " . $counts['applied'];
		$lines[] = "\t *    adapted:         " . $counts['adapted'];
		$lines[] = "\t *    kept:            " . $counts['kept'];
		$lines[] = "\t *    skipped:         " . $counts['skipped'];
		$lines[] = "\t */";
		$lines[] = '}';
		$lines[] = '';

		return implode("\n", $lines);
	}//end buildCss()

	/**
	 * A human label for an input kind, for the provenance block.
	 *
	 * @param string $kind The input kind letter.
	 *
	 * @return string The label.
	 */
	private function inputKindLabel(string $kind): string {
		$labels = [
			'A' => 'built theme CSS',
			'B' => 'W3C Design Tokens document',
			'C' => 'Style Dictionary tokens.json',
			'D' => 'existing token set, add-only',
		];

		return ($labels[$kind] ?? 'unknown');
	}//end inputKindLabel()

	/**
	 * Build the `token-sets.json` entry for a converted set.
	 *
	 * `theming.background_color` comes from the theme's PAGE background and is
	 * routed into Nextcloud's own theming rather than into
	 * `--color-main-background`, which stays Nextcloud-owned so dark mode keeps
	 * working.
	 *
	 * @param string                $slug          The set slug.
	 * @param string                $displayName   The display name.
	 * @param array<string, string> $semantic      The semantic layer.
	 * @param array<string, string> $manifest      Manifest values produced by the rules.
	 * @param string|null           $sourceName    The source label, when known.
	 * @param string|null           $sourceVersion The source version, when declared.
	 * @param array<string, mixed>|null $logo      The extracted logo, from {@see self::extractLogo()}.
	 *
	 * @return array<string, mixed> The manifest entry.
	 */
	private function buildManifestEntry(
		string $slug,
		string $displayName,
		array $semantic,
		array $manifest,
		?string $sourceName,
		?string $sourceVersion,
		?array $logo = null,
	): array {
		$theming = [];

		$primary = ($manifest['theming.primary_color'] ?? ($semantic['--nldesign-color-primary'] ?? null));
		if ($primary !== null) {
			$theming['primary_color'] = $primary;
		}

		$background = ($manifest['theming.background_color'] ?? null);
		if ($background !== null) {
			$theming['background_color'] = $background;
		}

		// The path the theming-sync dialog offers to Nextcloud's own logo slot.
		if ($logo !== null) {
			$theming['logo'] = $logo['path'];
		}

		$entry = [
			'id' => $slug,
			'name' => $displayName,
			'description' => 'Converted from ' . ($sourceName ?? 'a pasted design-system theme') . '.',
			'design_system' => 'nldesign',
		];

		if (empty($theming) === false) {
			$entry['theming'] = $theming;
		}

		if ($sourceName !== null) {
			$entry['upstreamRef'] = $sourceName;
		}

		if ($sourceVersion !== null) {
			$entry['upstreamVersion'] = $sourceVersion;
		}

		return $entry;
	}//end buildManifestEntry()
}//end class
