<?php

/**
 * Thematiq Token Reference Service.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * @category  Service
 * @package   OCA\Thematiq
 * @author    Conduction <info@conduction.nl>
 * @copyright 2026 Conduction B.V.
 * @license   EUPL-1.2 https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * @link      https://github.com/ConductionNL/thematiq
 *
 * @spec openspec/specs/token-reference/spec.md
 */

declare(strict_types=1);
namespace OCA\Thematiq\Service;

/**
 * Renders the token reference of one token set, as Markdown (the docs site and the download)
 * or as an HTML page (the in-app view): every token the set declares or inherits from the
 * defaults layer, its value and dark-mode value, where it comes from, and what it paints.
 * Output is deterministic: sorted, no timestamps.
 *
 * @spec openspec/specs/token-reference/spec.md
 *
 * @SuppressWarnings(PHPMD.StaticAccess) - TokenRegistry uses static methods by design.
 */
class TokenReferenceService {

	/**
	 * The stylesheets that turn `--nldesign-*` tokens into what Nextcloud and the components read.
	 *
	 * @var array<int, string>
	 */
	private const BRIDGES = ['css/systems/nldesign/overrides.css', 'css/systems/nldesign/utrecht-bridge.css'];

	/**
	 * Row groups in page order: heading, and the name fragments that put a token in it.
	 *
	 * @var array<string, array<int, string>>
	 */
	private const GROUPS = [
		'Colours (Kleuren)' => ['color', 'colour'],
		'Typography (Typografie)' => ['font', 'line-height', 'letter-spacing', 'text-'],
		'Spacing and shape (Ruimte en vorm)' => ['space', 'spacing', 'radius', 'border', 'size', 'width', 'height', 'gap', 'padding', 'margin'],
		'Other tokens (Overige tokens)' => [''],
	];

	/**
	 * The heading of the tokens nothing reads.
	 *
	 * @var string
	 */
	private const UNREAD = 'Tokens nothing reads (Tokens die niets leest)';

	/**
	 * How many consumers a row names before "and N more".
	 *
	 * @var integer
	 */
	private const MAX_PAINTS = 5;

	/**
	 * Constructor.
	 *
	 * @param ShippedTokenSetAuditService $audit  The contrast audit, for the summary line.
	 * @param CssParserService            $parser The CSS parser.
	 */
	public function __construct(
		private ShippedTokenSetAuditService $audit,
		private CssParserService $parser,
	) {
	}//end __construct()

	/**
	 * Render the reference of one set.
	 *
	 * @param string               $appPath The app root.
	 * @param array<string, mixed> $set     The set: `id`, `name`, `theming`.
	 * @param string               $format  `md` or `html`.
	 *
	 * @return string The reference.
	 *
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-docs-site-has-a-reference-page-per-shipped-set
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-reference-does-not-rely-on-colour-alone
	 */
	public function render(string $appPath, array $set, string $format): string {
		$model = $this->model(appPath: $appPath, set: $set);
		if ($format === 'html') {
			return $this->html(model: $model);
		}

		return $this->markdown(model: $model);
	}//end render()

	/**
	 * Every docs page: one per shipped set with a token file, and an index.
	 *
	 * @param string $appPath The app root.
	 *
	 * @return array<string, string> File name under docs/reference/token-sets/ => content.
	 *
	 * @spec openspec/specs/token-reference/spec.md#requirement-the-docs-site-has-a-reference-page-per-shipped-set
	 */
	public function docsPages(string $appPath): array {
		$manifest = json_decode((string)file_get_contents($appPath . '/token-sets.json'), true);
		$sets = [];
		foreach ((is_array($manifest) === true ? $manifest : []) as $set) {
			if (is_array($set) === true && is_string($set['id'] ?? null) === true && is_file($appPath . '/css/tokens/' . $set['id'] . '.css') === true) {
				$sets[$set['id']] = $set;
			}
		}

		ksort($sets);
		$pages = [];
		$index = [
			'<!-- GENERATED by TokenReferenceService, do not edit by hand. Regenerate with: composer docs:token-reference -->',
			'',
			'# Token sets',
			'',
			'The tokens of every shipped token set: the value, the dark-mode value, whether it comes from the set or from the defaults layer, and what it paints. Signed-in users also find the reference of custom sets in Nextcloud, under Settings > Administration > Theming.',
			'',
		];
		foreach ($sets as $id => $set) {
			$pages[$id . '.md'] = $this->render(appPath: $appPath, set: $set, format: 'md');
			$index[] = '- [' . $this->mdText(text: (string)($set['name'] ?? $id)) . '](./' . $id . '.md) `' . $id . '`';
		}

		$pages['index.md'] = implode("\n", $index) . "\n";
		ksort($pages);

		return $pages;
	}//end docsPages()

	/**
	 * Resolve the rows of one set.
	 *
	 * @param string               $appPath The app root.
	 * @param array<string, mixed> $set     The set.
	 *
	 * @return array{id: string, name: string, declared: int, inherited: int, contrast: string, groups: array<string, array<int, array<string, mixed>>>}
	 */
	private function model(string $appPath, array $set): array {
		$id = (string)$set['id'];
		$defaults = $this->parseFile(path: $appPath . '/css/systems/nldesign/defaults.css');
		$own = $this->parseFile(path: $appPath . '/css/tokens/' . $id . '.css');
		$dark = $this->parseAny(path: $appPath . '/css/tokens/dark/' . $id . '.css');
		$consumers = $this->consumers(appPath: $appPath);

		$names = array_unique(array_merge(array_keys($defaults), array_keys($own)));
		sort($names);
		$groups = array_fill_keys(array_merge(array_keys(self::GROUPS), [self::UNREAD]), []);
		foreach ($names as $name) {
			$declared = array_key_exists($name, $own);
			$row = [
				'name' => $name,
				'value' => ($own[$name] ?? $defaults[$name]),
				'dark' => ($dark[$name] ?? ''),
				'source' => ($declared === true ? 'this set' : 'defaults'),
				'paints' => ($consumers[$name] ?? []),
			];
			$group = $this->groupOf(name: $name);
			if ($declared === true && array_key_exists($name, $defaults) === false && $row['paints'] === []) {
				$group = self::UNREAD;
			}

			$groups[$group][] = $row;
		}

		return [
			'id' => $id,
			'name' => (string)($set['name'] ?? $id),
			'declared' => count($own),
			'inherited' => count(array_diff_key($defaults, $own)),
			'contrast' => $this->contrastLine(appPath: $appPath, id: $id, theming: (array)($set['theming'] ?? [])),
			'groups' => array_filter($groups),
		];
	}//end model()

	/**
	 * The `:root` declarations of a file, or none when it is absent.
	 *
	 * @param string $path The file.
	 *
	 * @return array<string, string> Name => value.
	 */
	private function parseFile(string $path): array {
		if (is_file($path) === false) {
			return [];
		}

		return $this->parser->parseRootBlock(css: (string)file_get_contents($path));
	}//end parseFile()

	/**
	 * Every custom property in a file, whatever block holds it; the first declaration wins.
	 * A dark variant keeps its tokens in an `@media` block and a `[data-theme-dark]` block, not in `:root`.
	 *
	 * @param string $path The file.
	 *
	 * @return array<string, string> Name => value.
	 */
	private function parseAny(string $path): array {
		if (is_file($path) === false) {
			return [];
		}

		preg_match_all('/(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]+);/', (string)file_get_contents($path), $matches, PREG_SET_ORDER);
		$result = [];
		foreach ($matches as $match) {
			if (isset($result[$match[1]]) === false) {
				$result[$match[1]] = trim($match[2]);
			}
		}

		return $result;
	}//end parseAny()

	/**
	 * Which properties read each `--nldesign-*` token, with the registry label where there is one.
	 *
	 * @param string $appPath The app root.
	 *
	 * @return array<string, array<int, string>> Token => sorted, unique consumer descriptions.
	 */
	private function consumers(string $appPath): array {
		$labels = TokenRegistry::getTokens();
		$map = [];
		foreach (self::BRIDGES as $bridge) {
			$css = (string)@file_get_contents($appPath . '/' . $bridge);
			preg_match_all('/(--[A-Za-z0-9_-]+)\s*:\s*([^;{}]*)/', $css, $matches, PREG_SET_ORDER);
			foreach ($matches as $match) {
				preg_match_all('/var\(\s*(--nldesign-[A-Za-z0-9_-]+)/', $match[2], $reads);
				foreach ($reads[1] as $token) {
					$map[$token][] = (string)($labels[$match[1]]['label'] ?? '`' . $match[1] . '`');
				}
			}
		}

		foreach ($map as $token => $list) {
			$list = array_values(array_unique($list));
			sort($list);
			$map[$token] = $list;
		}

		return $map;
	}//end consumers()

	/**
	 * The group heading of a token.
	 *
	 * @param string $name The token name.
	 *
	 * @return string The heading.
	 */
	private function groupOf(string $name): string {
		foreach (self::GROUPS as $heading => $fragments) {
			foreach ($fragments as $fragment) {
				if ($fragment === '' || str_contains($name, $fragment) === true) {
					return $heading;
				}
			}
		}

		return 'Other tokens (Overige tokens)';
	}//end groupOf()

	/**
	 * The contrast summary of the set.
	 *
	 * @param string               $appPath The app root.
	 * @param string               $id      The set id.
	 * @param array<string, mixed> $theming The set's theming block.
	 *
	 * @return string The sentence.
	 */
	private function contrastLine(string $appPath, string $id, array $theming): string {
		$result = $this->audit->auditSet(appPath: $appPath, id: $id, theming: $theming);

		return sprintf(
			'Contrast: primary text on primary %s, primary on background %s (%s).',
			$this->ratio(value: $result['textRatio']),
			$this->ratio(value: $result['uiRatio']),
			$result['verdict']
		);
	}//end contrastLine()

	/**
	 * A ratio as text.
	 *
	 * @param float|null $value The ratio.
	 *
	 * @return string `4.62:1`, or `not evaluated`.
	 */
	private function ratio(?float $value): string {
		if ($value === null) {
			return 'not evaluated';
		}

		return number_format($value, 2) . ':1';
	}//end ratio()

	/**
	 * Whether a value is a literal colour a swatch can show.
	 *
	 * @param string $value The value.
	 *
	 * @return boolean True for hex, rgb(a) and hsl(a) literals.
	 */
	private function isColour(string $value): bool {
		return preg_match('/^(#[0-9a-fA-F]{3,8}|(rgb|hsl)a?\([0-9.,%\s\/deg]+\))$/', trim($value)) === 1;
	}//end isColour()

	/**
	 * The Markdown page.
	 *
	 * @param array<string, mixed> $model The resolved rows.
	 *
	 * @return string Markdown.
	 */
	private function markdown(array $model): string {
		$lines = [
			'<!-- GENERATED by TokenReferenceService, do not edit by hand. Regenerate with: composer docs:token-reference -->',
			'',
			'# ' . $this->mdText(text: $model['name']),
			'',
			sprintf('Token set `%s`: %d declared by this set, %d from the defaults layer.', $model['id'], $model['declared'], $model['inherited']),
			'',
			$model['contrast'],
		];
		foreach ($model['groups'] as $heading => $rows) {
			array_push($lines, '', '## ' . $heading, '', '| Token | Value | Dark mode | Source | Paints |', '|---|---|---|---|---|');
			foreach ($rows as $row) {
				$cells = ['`' . $row['name'] . '`', $this->mdValue(value: $row['value']), $this->mdValue(value: $row['dark']), $row['source'], $this->paints(list: $row['paints'])];
				$lines[] = str_replace('|  |', '| |', '| ' . implode(' | ', $cells) . ' |');
			}
		}

		return implode("\n", $lines) . "\n";
	}//end markdown()

	/**
	 * A value cell: a swatch for a colour, then the value as code.
	 *
	 * @param string $value The value, or ''.
	 *
	 * @return string The cell.
	 */
	private function mdValue(string $value): string {
		if ($value === '') {
			return '';
		}

		$code = '`' . str_replace(['`', '|'], ["'", '\\|'], $value) . '`';
		if ($this->isColour(value: $value) === false) {
			return $code;
		}

		// Fully percent-encoded, so the URL holds no space or quote a Markdown link would stop at.
		$svg = rawurlencode(
			'<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14"><rect width="14" height="14" fill="' . trim($value) . '"/></svg>'
		);

		return '![](data:image/svg+xml,' . $svg . ') ' . $code;
	}//end mdValue()

	/**
	 * Text safe inside a Markdown line.
	 *
	 * @param string $text The text.
	 *
	 * @return string The text without characters Markdown or MDX would read as markup.
	 */
	private function mdText(string $text): string {
		return str_replace(['<', '>', '{', '}', '|', '[', ']'], ['', '', '', '', '', '(', ')'], $text);
	}//end mdText()

	/**
	 * The paints cell.
	 *
	 * @param array<int, string> $list The consumers.
	 *
	 * @return string The cell.
	 */
	private function paints(array $list): string {
		if (count($list) <= self::MAX_PAINTS) {
			return implode(', ', $list);
		}

		return implode(', ', array_slice($list, 0, self::MAX_PAINTS)) . ' and ' . (count($list) - self::MAX_PAINTS) . ' more';
	}//end paints()

	/**
	 * The HTML page.
	 *
	 * @param array<string, mixed> $model The resolved rows.
	 *
	 * @return string HTML.
	 */
	private function html(array $model): string {
		$name = $this->esc(text: $model['name']);
		$out = '<!DOCTYPE html>' . "\n" . '<html lang="en">' . "\n" . '<head>' . "\n" . '<meta charset="utf-8">' . "\n"
			. '<title>' . $name . ' token reference</title>' . "\n"
			. '<style>body{font-family:sans-serif;color:#1a1a1a;background:#fff;margin:2em;line-height:1.5}'
			. 'table{border-collapse:collapse;margin-bottom:2em}th,td{border:1px solid #767676;padding:4px 8px;text-align:left;vertical-align:top}'
			. '.swatch{display:inline-block;width:1em;height:1em;border:1px solid #767676;vertical-align:middle}'
			. 'summary{cursor:pointer;font-weight:bold}</style>' . "\n" . '</head>' . "\n" . '<body>' . "\n" . '<main>' . "\n"
			. '<h1>' . $name . '</h1>' . "\n"
			. '<p>' . sprintf('Token set <code>%s</code>: %d declared by this set, %d from the defaults layer.', $this->esc(text: $model['id']), $model['declared'], $model['inherited']) . '</p>' . "\n"
			. '<p>' . $this->esc(text: $model['contrast']) . '</p>' . "\n";
		foreach ($model['groups'] as $heading => $rows) {
			$table = $this->htmlTable(rows: $rows);
			if ($heading === self::UNREAD) {
				$out .= '<details>' . "\n" . '<summary>' . $this->esc(text: $heading) . '</summary>' . "\n" . $table . '</details>' . "\n";
				continue;
			}

			$out .= '<h2>' . $this->esc(text: $heading) . '</h2>' . "\n" . $table;
		}

		return $out . '</main>' . "\n" . '</body>' . "\n" . '</html>' . "\n";
	}//end html()

	/**
	 * One HTML table.
	 *
	 * @param array<int, array<string, mixed>> $rows The rows.
	 *
	 * @return string HTML.
	 */
	private function htmlTable(array $rows): string {
		$out = '<table>' . "\n" . '<thead><tr><th scope="col">Token</th><th scope="col">Value</th><th scope="col">Dark mode</th>'
			. '<th scope="col">Source</th><th scope="col">Paints</th></tr></thead>' . "\n" . '<tbody>' . "\n";
		foreach ($rows as $row) {
			$out .= '<tr><td><code>' . $this->esc(text: $row['name']) . '</code></td><td>' . $this->htmlValue(value: $row['value']) . '</td><td>'
				. $this->htmlValue(value: $row['dark']) . '</td><td>' . $row['source'] . '</td><td>'
				. $this->esc(text: str_replace('`', '', $this->paints(list: $row['paints']))) . '</td></tr>' . "\n";
		}

		return $out . '</tbody>' . "\n" . '</table>' . "\n";
	}//end htmlTable()

	/**
	 * A value cell in HTML: a decorative swatch for a colour, then the value as code.
	 *
	 * @param string $value The value, or ''.
	 *
	 * @return string HTML.
	 */
	private function htmlValue(string $value): string {
		if ($value === '') {
			return '';
		}

		$code = '<code>' . $this->esc(text: $value) . '</code>';
		if ($this->isColour(value: $value) === false) {
			return $code;
		}

		return '<span class="swatch" aria-hidden="true" style="background:' . $this->esc(text: trim($value)) . '"></span> ' . $code;
	}//end htmlValue()

	/**
	 * Escape text for HTML.
	 *
	 * @param string $text The text.
	 *
	 * @return string Escaped.
	 */
	private function esc(string $text): string {
		return htmlspecialchars($text, ENT_QUOTES | ENT_HTML5, 'UTF-8');
	}//end esc()
}//end class
