#!/usr/bin/env node
/**
 * Build script for NL Design System Icons
 *
 * Materializes two kinds of redistributable government icon packs into standalone SVG
 * files under img/icons/{set}/{key}.svg:
 *
 * - `kind: 'dataUri'` — the EUPL-compatible NL-government packs bundled in
 *   @conduction/nextcloud-vue (src/icons/{rvo,openGemeenten,denHaag}.js — data-URI
 *   catalogue modules, auto-generated by nextcloud-vue's scripts/generate-nl-icons.mjs).
 *   Each pack entry's data:image/svg+xml URI is decoded into a standalone file.
 * - `kind: 'glob'` — the French-government DSFR pack from @gouvfr/dsfr
 *   (dist/icons/**\/*.svg — real SVG files under category subdirectories). Every source
 *   SVG is copied to img/icons/dsfr/{basename}.svg (category prefix dropped; DSFR names
 *   are unique across the whole set — referenced globally as `.fr-icon-<name>` in DSFR
 *   CSS — so the flat layout is collision-free; the build fails on a duplicate basename).
 *   @gouvfr/dsfr currently cannot be npm-installed (broken optional dependencies
 *   upstream), so the source tree is read from the first of two candidate directories
 *   that exists: the real npm package path (correct once that's fixed upstream), or the
 *   pre-fetched scratch source `.dsfr-src/icons/` (gitignored — never committed; see
 *   openspec/changes/theme-switchable-iconography). This is icons ONLY: the Marianne
 *   typeface files shipped in the same @gouvfr/dsfr package are FR-state-restricted and
 *   MUST NOT be bundled by this script.
 *
 * @conduction/nextcloud-vue and @gouvfr/dsfr are devDependencies consumed ONLY by this
 * build script — nothing under js/ or lib/ imports them; nldesign remains a no-Vue app
 * and ships no runtime JS dependency on either package.
 *
 * This script does NOT copy anything from the proprietary Amsterdam Design System icon
 * package (that dependency is removed — see CHANGELOG.md) and does NOT touch img/logos/ —
 * the 23 organisation logos are static, checked-in huisstijl assets, not build output
 * (see img/ICONS.md).
 *
 * For exactly one release, a curated alias map (scripts/icon-aliases.json) additionally
 * writes replacement artwork under legacy Amsterdam PascalCase filenames at the
 * top-level img/icons/{Name}.svg, so URLs stored by consumers before this change
 * (e.g. launchpad tile data) keep resolving — always to EUPL-compatible replacement
 * bytes, never to Amsterdam artwork. Unmapped legacy names simply 404. See
 * scripts/icon-aliases.json and img/ICONS.md for the removal deadline.
 */

const fs = require('fs')
const os = require('os')
const path = require('path')
const { pathToFileURL } = require('url')

/**
 * Import one of nextcloud-vue's icon modules.
 *
 * They are ES modules (`export const rvoIcons = [...]`) in a package that does
 * not declare `"type": "module"`, and a Node older than 20.19 reads such a `.js`
 * file as CommonJS and stops at `export`. A `.mjs` copy is an ES module on every
 * Node; the files import nothing, so the copy can live anywhere.
 *
 * @param {string} specifier The module, e.g. `@conduction/nextcloud-vue/src/icons/rvo.js`.
 * @return {Promise<object>} The module's exports.
 */
async function importIconModule(specifier) {
	const source = path.join(__dirname, '..', 'node_modules', specifier)
	const copy = path.join(
		os.tmpdir(),
		`thematiq-${process.pid}-${path.basename(source, '.js')}.mjs`,
	)
	fs.copyFileSync(source, copy)
	try {
		return await import(pathToFileURL(copy).href)
	} finally {
		fs.rmSync(copy, { force: true })
	}
}

const iconsDestPath = path.join(__dirname, '..', 'img', 'icons')
const logosDestPath = path.join(__dirname, '..', 'img', 'logos')
const iconsMdPath = path.join(__dirname, '..', 'img', 'ICONS.md')
const aliasesPath = path.join(__dirname, 'icon-aliases.json')

/** Data-URI catalogue packs: nc-vue module -> destination set directory name. */
const DATA_URI_PACKS = [
	{
		kind: 'dataUri',
		specifier: '@conduction/nextcloud-vue/src/icons/rvo.js',
		exportName: 'rvoIcons',
		set: 'rvo',
		upstream: 'RVO / ROOS (Rijksdienst voor Ondernemend Nederland)',
		licence: 'CC0-1.0',
	},
	{
		kind: 'dataUri',
		specifier: '@conduction/nextcloud-vue/src/icons/openGemeenten.js',
		exportName: 'openGemeentenIcons',
		set: 'open-gemeenten',
		upstream: 'OpenGemeenten Iconenset ("Line" style)',
		licence: 'CC0-1.0',
	},
	{
		kind: 'dataUri',
		specifier: '@conduction/nextcloud-vue/src/icons/denHaag.js',
		exportName: 'denHaagIcons',
		set: 'den-haag',
		upstream: 'Gemeente Den Haag icon set',
		licence: 'EUPL-1.2',
	},
]

/** Filesystem-glob packs: real SVG files copied verbatim, keyed by basename. */
const GLOB_PACKS = [
	{
		kind: 'glob',
		set: 'dsfr',
		upstream: "Système de Design de l'État (DSFR) — @gouvfr/dsfr",
		licence: 'Etalab-2.0',
		// First existing directory wins: the real npm package path (per
		// openspec/specs/icon-assets/spec.md), falling back to the pre-fetched
		// scratch source — see the file docblock above.
		sourceDirs: [
			path.join(
				__dirname,
				'..',
				'node_modules',
				'@gouvfr',
				'dsfr',
				'dist',
				'icons',
			),
			path.join(__dirname, '..', '.dsfr-src', 'icons'),
		],
	},
]

const DATA_URI_PREFIX = 'data:image/svg+xml,'

/**
 * Decode a nc-vue pack entry's data:image/svg+xml,... URI back into raw SVG markup.
 * The generator (nextcloud-vue/scripts/generate-nl-icons.mjs) encodes with a plain
 * encodeURIComponent (plus a few characters decoded back for readability), so a plain
 * decodeURIComponent is an exact inverse.
 */
function decodeDataUri(url) {
	if (!url.startsWith(DATA_URI_PREFIX)) {
		throw new Error(
			`Unexpected icon URL format (missing ${DATA_URI_PREFIX} prefix): ${url.slice(0, 40)}...`,
		)
	}
	return decodeURIComponent(url.slice(DATA_URI_PREFIX.length))
}

/** Recreate a directory empty (idempotent regenerate). */
function resetDir(dir) {
	fs.rmSync(dir, { recursive: true, force: true })
	fs.mkdirSync(dir, { recursive: true })
}

/**
 * Recursively collect every *.svg file under `dir` (depth-first, any nesting
 * of category subdirectories). Used for the DSFR glob pack — plain fs
 * recursion rather than a glob dependency or the still-experimental
 * fs.globSync, so the script stays dependency-free and Node-version-stable.
 */
function listSvgFilesRecursive(dir) {
	const results = []
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name)
		if (entry.isDirectory()) {
			results.push(...listSvgFilesRecursive(full))
		} else if (entry.isFile() && entry.name.toLowerCase().endsWith('.svg')) {
			results.push(full)
		}
	}
	return results
}

/**
 * Read an already-materialized pack directory back into memory, as
 * `{ basename -> svg }`, sorted by basename so the regenerated inventory is
 * byte-stable regardless of readdir order.
 *
 * Used to carry a glob pack across `resetDir()` when its upstream source tree
 * is not installable — see the GLOB_PACKS loop for why that is a supported
 * state rather than an error.
 */
function snapshotPackDir(dir) {
	/** @type {Map<string, string>} */
	const snapshot = new Map()
	if (fs.existsSync(dir) === false || fs.statSync(dir).isDirectory() === false) {
		return snapshot
	}
	const files = fs
		.readdirSync(dir)
		.filter((f) => f.toLowerCase().endsWith('.svg'))
		.sort()
	for (const file of files) {
		snapshot.set(
			path.basename(file, '.svg'),
			fs.readFileSync(path.join(dir, file), 'utf8'),
		)
	}
	return snapshot
}

async function main() {
	console.log(
		'Building NL Design System Icons from @conduction/nextcloud-vue and @gouvfr/dsfr...',
	)

	// Snapshot every glob pack's already-committed artefacts BEFORE the wipe.
	//
	// `resetDir()` below deletes img/icons/ wholesale, which is correct for the
	// data-URI packs (always regenerable from @conduction/nextcloud-vue, a real
	// dependency). It is NOT safe for a glob pack whose source is an OPTIONAL
	// dependency: @gouvfr/dsfr is declared in `optionalDependencies` precisely
	// because it currently cannot be npm-installed (broken optional deps
	// upstream), and its documented fallback `.dsfr-src/icons/` is gitignored.
	// On any clean checkout — every CI runner — neither candidate source
	// directory exists, so the wipe destroyed 1038 committed icons and the
	// script then exited 1. `npm run build` could not succeed anywhere except a
	// developer box that had manually pre-fetched the source.
	/** @type {Map<string, Map<string, string>>} */
	const committedGlobPacks = new Map()
	for (const pack of GLOB_PACKS) {
		committedGlobPacks.set(
			pack.set,
			snapshotPackDir(path.join(iconsDestPath, pack.set)),
		)
	}

	// Load every data-URI pack BEFORE the wipe as well: an import that fails
	// (an old Node, a package that moved) must stop the build with img/icons/
	// untouched, not after it has been emptied.
	/** @type {Map<string, object>} */
	const loadedPacks = new Map()
	for (const pack of DATA_URI_PACKS) {
		loadedPacks.set(pack.set, await importIconModule(pack.specifier))
	}

	resetDir(iconsDestPath)

	/** @type {Map<string, { icons: Array<{id: string, label?: string, url?: string}>, upstream: string, licence: string }>} */
	const packData = new Map()
	/** @type {Map<string, string>} set/key -> decoded SVG content, for alias resolution */
	const svgByPath = new Map()

	for (const pack of DATA_URI_PACKS) {
		const mod = loadedPacks.get(pack.set)
		const icons = mod[pack.exportName]
		if (!Array.isArray(icons) || icons.length === 0) {
			console.error(
				`✗ Pack "${pack.set}" (${pack.specifier}) yielded zero icons.`,
			)
			process.exit(1)
		}

		const setDir = path.join(iconsDestPath, pack.set)
		fs.mkdirSync(setDir, { recursive: true })

		for (const entry of icons) {
			const svg = decodeDataUri(entry.url)
			const destFile = path.join(setDir, `${entry.id}.svg`)
			fs.writeFileSync(destFile, svg)
			svgByPath.set(`${pack.set}/${entry.id}`, svg)
		}

		packData.set(pack.set, {
			icons,
			upstream: pack.upstream,
			licence: pack.licence,
		})
		console.log(
			`✓ Materialized ${icons.length} icons for set "${pack.set}" -> ${setDir}`,
		)
	}

	for (const pack of GLOB_PACKS) {
		const sourceDir = pack.sourceDirs.find(
			(d) => fs.existsSync(d) && fs.statSync(d).isDirectory(),
		)
		if (sourceDir === undefined) {
			// The upstream source is unavailable. That is an EXPECTED state for
			// this pack, not a build error: @gouvfr/dsfr sits in
			// `optionalDependencies` because it cannot currently be
			// npm-installed, and the documented scratch fallback
			// `.dsfr-src/icons/` is gitignored — so neither candidate exists on
			// a clean checkout. The sibling script scripts/build-fonts-marianne.js
			// already treats exactly this condition as a warning ("0 is
			// expected/harmless when @gouvfr/dsfr is not installed") and leaves
			// its committed artefacts alone; this pack now does the same.
			//
			// Reuse the committed artefacts snapshotted before resetDir(). This
			// is deliberately NOT a skip: the pack is still fully materialized,
			// so `packData` keeps its licence/upstream attribution, ICONS.md
			// regenerates with the identical inventory, and the alias shim can
			// still resolve `dsfr/*` replacements. Skipping would silently drop
			// 1038 icons and the Etalab-2.0 attribution row out of a COMMITTED
			// file, which is a far worse failure than the one being fixed.
			const committed = committedGlobPacks.get(pack.set) ?? new Map()
			if (committed.size === 0) {
				console.error(
					`✗ Pack "${pack.set}" has no available source directory (tried: ${pack.sourceDirs.join(', ')}) and no committed icons under ${path.join(iconsDestPath, pack.set)} to fall back on.`,
				)
				process.exit(1)
			}

			const setDir = path.join(iconsDestPath, pack.set)
			fs.mkdirSync(setDir, { recursive: true })
			const icons = []
			for (const [basename, svg] of committed) {
				fs.writeFileSync(path.join(setDir, `${basename}.svg`), svg)
				svgByPath.set(`${pack.set}/${basename}`, svg)
				icons.push({ id: basename })
			}

			packData.set(pack.set, {
				icons,
				upstream: pack.upstream,
				licence: pack.licence,
			})
			console.log(
				`⚠ Pack "${pack.set}": no source directory available (tried: ${pack.sourceDirs.join(', ')}).`,
			)
			console.log(
				`✓ Preserved ${icons.length} already-committed icons for set "${pack.set}" -> ${setDir}`,
			)
			console.log(
				'  To refresh from upstream: npm install --no-save @gouvfr/dsfr@1.15.1 && npm run build:icons',
			)
			continue
		}

		const sourceFiles = listSvgFilesRecursive(sourceDir)
		if (sourceFiles.length === 0) {
			console.error(`✗ Pack "${pack.set}" (${sourceDir}) yielded zero icons.`)
			process.exit(1)
		}

		const setDir = path.join(iconsDestPath, pack.set)
		fs.mkdirSync(setDir, { recursive: true })

		/** @type {Map<string, string>} basename -> source file path, to detect duplicates */
		const seenBasenames = new Map()
		const icons = []
		for (const file of sourceFiles) {
			const basename = path.basename(file, path.extname(file))
			const previous = seenBasenames.get(basename)
			if (previous !== undefined) {
				console.error(
					`✗ Pack "${pack.set}" has a duplicate icon basename "${basename}": "${previous}" and "${file}".`,
				)
				process.exit(1)
			}
			seenBasenames.set(basename, file)

			const svg = fs.readFileSync(file, 'utf8')
			const destFile = path.join(setDir, `${basename}.svg`)
			fs.writeFileSync(destFile, svg)
			svgByPath.set(`${pack.set}/${basename}`, svg)
			icons.push({ id: basename })
		}

		// Sort by id before recording. `listSvgFilesRecursive` returns
		// source-tree order (category directory by category directory), which
		// is an upstream layout detail that leaks straight into the committed
		// img/ICONS.md inventory sample. The materialized pack is FLAT — the
		// category prefix is dropped — so that ordering is not reconstructible
		// from the committed artefacts, and the fallback path above can only
		// ever produce sorted order. Sorting here too makes ICONS.md identical
		// whether or not the optional upstream source happens to be installed,
		// instead of flip-flopping the committed file between the two.
		icons.sort((a, b) => a.id.localeCompare(b.id))

		packData.set(pack.set, {
			icons,
			upstream: pack.upstream,
			licence: pack.licence,
		})
		console.log(
			`✓ Materialized ${icons.length} icons for set "${pack.set}" -> ${setDir} (source: ${sourceDir})`,
		)
	}

	// Legacy Amsterdam filename aliases (one-release deprecation shim).
	const aliasesRaw = JSON.parse(fs.readFileSync(aliasesPath, 'utf8'))
	const aliases = Object.fromEntries(
		Object.entries(aliasesRaw).filter(([key]) => key !== '_comment'),
	)

	let aliasCount = 0
	for (const [legacyName, replacementPath] of Object.entries(aliases)) {
		const svg = svgByPath.get(replacementPath)
		if (svg === undefined) {
			console.error(
				`✗ scripts/icon-aliases.json maps "${legacyName}" to unknown replacement "${replacementPath}".`,
			)
			process.exit(1)
		}
		fs.writeFileSync(path.join(iconsDestPath, `${legacyName}.svg`), svg)
		aliasCount++
	}
	console.log(
		`✓ Materialized ${aliasCount} legacy-name alias files (one-release deprecation shim)`,
	)

	// img/logos/ is a static, checked-in directory — never created, modified, or written here.
	const logoCount = fs.existsSync(logosDestPath)
		? fs.readdirSync(logosDestPath).filter((f) => f.endsWith('.svg')).length
		: 0

	writeIconsMd({ packData, aliases, logoCount })
	console.log(`✓ Regenerated ${iconsMdPath}`)

	const totalIcons = [...packData.values()].reduce(
		(sum, p) => sum + p.icons.length,
		0,
	)
	console.log(
		`\n✅ Icon build complete! ${totalIcons} icons across ${packData.size} sets + ${aliasCount} legacy aliases + ${logoCount} logos (untouched).`,
	)
}

/**
 * Regenerate img/ICONS.md: per-set inventories with licence/upstream attribution,
 * the legacy-alias table with its removal deadline, the PHP usage snippet, the
 * availability/fallback + naming-stability sections, and a Logos section.
 */
function writeIconsMd({ packData, aliases, logoCount }) {
	const setSections = [...packData.entries()]
		.map(([set, data]) => {
			const sample = data.icons
				.slice(0, 20)
				.map((i) => `- ${set}/${i.id}`)
				.join('\n')
			const more =
				data.icons.length > 20
					? `\n... and ${data.icons.length - 20} more`
					: ''
			return `### ${set} (${data.icons.length} icons)

Upstream: ${data.upstream}
Licence: **${data.licence}**
Available in: \`img/icons/${set}/\`

${sample}${more}`
		})
		.join('\n\n')

	const aliasRows = Object.entries(aliases)
		.map(
			([legacy, replacement]) =>
				`| \`${legacy}.svg\` | \`${replacement}.svg\` |`,
		)
		.join('\n')

	const logoFiles = fs.existsSync(logosDestPath)
		? fs
				.readdirSync(logosDestPath)
				.filter((f) => f.endsWith('.svg'))
				.map((f) => f.replace('.svg', ''))
		: []

	const content = `# NL-Government & French-Government Icons, and Logos

This directory contains SVG icons materialized from the EUPL-compatible NL-government
icon packs bundled in \`@conduction/nextcloud-vue\` (\`src/icons/{rvo,openGemeenten,denHaag}.js\`),
the French-government DSFR pack from \`@gouvfr/dsfr\` (\`dist/icons/**/*.svg\`), plus the
organisation logos in \`img/logos/\`.

**The proprietary City-of-Amsterdam icon set (\`@amsterdam/design-system-assets\`) is NOT
bundled.** Its \`LICENSE.md\` marks the set proprietary to the City of Amsterdam ("The
open-source licence does NOT apply to files in this directory"), restricted to contexts
where Amsterdam is the main communicator — redistributing it to arbitrary Dutch-government
Nextcloud instances is exactly the use its notice forbids. It was removed from this app;
see CHANGELOG.md for the full list of removed filenames and their replacements.

## Icons

${setSections}

DSFR filenames (\`dsfr/{basename}.svg\`) are the source SVG's basename with its category
prefix dropped (e.g. \`dist/icons/arrows/arrow-right-line.svg\` -> \`dsfr/arrow-right-line.svg\`):
DSFR icon names are unique across the whole set (referenced globally in DSFR CSS as
\`.fr-icon-<name>\`), so this flat, category-free layout is collision-free — the build fails
on any duplicate basename.

## Icon-pack resolution (theme-switchable iconography)

The icon pack an app should serve travels with the active **design system**, not a fixed
set: \`design-systems.json\` carries an optional \`icon_pack\` field per design system
(\`nldesign\` -> \`["rvo", "open-gemeenten", "den-haag"]\`, \`lasuite\` -> \`["dsfr"]\`; a design
system without the field serves no pack — Nextcloud stock icons apply). Resolution is
\`active token set -> its design_system -> that design system's icon_pack\`, with an
appconfig \`icon_pack\` admin override taking precedence when it names a real pack
directory. Consumers who want a **fixed** pack keep using
\`imagePath('nldesign', 'icons/{set}/{key}.svg')\` exactly as before (unchanged, non-breaking).
Consumers who want the **active theme's** pack should resolve it through
\`DesignSystemService::resolveActiveIconPacks()\` / \`resolveIconPath()\`, or read the
resolved list from the public capability (\`/ocs/v2.php/cloud/capabilities\` ->
\`capabilities.nldesign.iconPacks\`) — see \`openspec/specs/icon-packs/spec.md\`.

**Honest limitation:** this only switches nldesign's own bundled icon assets (the ones
served through \`imagePath\` and the capability above). It does NOT force-replace
Nextcloud core's built-in icon set (navigation, files, the Material-style core icons)
beyond what the active theme's CSS already restyles.

## Licence attribution

Canonical licence record for the NL packs: \`@conduction/nextcloud-vue\`'s
\`src/icons/ATTRIBUTION.md\` (https://github.com/ConductionNL/nextcloud-vue/blob/main/src/icons/ATTRIBUTION.md).
The DSFR pack is licensed under the Etalab Open Licence 2.0
(https://github.com/etalab/licence-ouverte/blob/master/LO.md), redistributed via
\`@gouvfr/dsfr\` — Système de Design de l'État (https://www.systeme-de-design.gouv.fr/).
This materialization is **icons only**: the Marianne typeface files shipped in the same
\`@gouvfr/dsfr\` package are FR-state-restricted and are never bundled by this script.

| Set | Upstream | Licence |
| --- | --- | --- |
${[...packData.entries()].map(([set, data]) => `| \`${set}\` | ${data.upstream} | **${data.licence}** |`).join('\n')}

## Legacy Amsterdam filename aliases (one-release deprecation)

For exactly **one release**, the legacy Amsterdam Design System filenames listed below
resolve to a top-level \`img/icons/{Name}.svg\` file — a byte-identical copy of the mapped
replacement artwork below, never Amsterdam artwork. **These aliases are removed in the
next minor release** (\`scripts/icon-aliases.json\` emptied, the build stops emitting
top-level files). Any legacy name NOT in this table returns HTTP 404 today; see
CHANGELOG.md for the full list of names removed without a replacement.

| Legacy path (deprecated) | Replacement artwork |
| --- | --- |
${aliasRows}

## Usage in Nextcloud

\`\`\`php
// In your template or controller — a FIXED pack, regardless of the active theme
<img src="<?php p(\\OC::$server->getURLGenerator()->imagePath('nldesign', 'icons/rvo/rvo-zoek.svg')); ?>" alt="Search">
<img src="<?php p(\\OC::$server->getURLGenerator()->imagePath('nldesign', 'icons/dsfr/arrow-right-line.svg')); ?>" alt="Next">
\`\`\`

Vue-based consumers SHOULD prefer importing the NL packs from \`@conduction/nextcloud-vue\`
directly (e.g. \`CnIconBrowser\` \`url-icons\`); the \`imagePath\` contract above exists for
PHP/template and other non-Vue consumers.

These URLs only resolve while the nldesign app is enabled. Consumers must ship a fallback
icon or declare a dependency on \`nldesign\`.

## Logos (${logoCount} total)

Available in: \`img/logos/\`. Static, checked-in huisstijl assets tied to token sets
(\`token-sets.json\` \`theming.logo\` entries) — organisation marks displayed as that
organisation's own identity on that organisation's own instance. **Not build output**:
\`scripts/build-icons.js\` never creates, modifies, or deletes anything under \`img/logos/\`.

${logoFiles.map((f) => `- ${f}`).join('\n')}

## Naming stability (public API)

Icon and logo filenames are a public API consumed by other apps. Within an installed
source pack version, renaming or removing a bundled icon or logo is a **breaking change**:
record it in the changelog (old + new name) and regenerate this file in the same change so
the inventory regression test (\`tests/Unit/IconAssetsTest.php\`) keeps passing. Upgrading a
source dependency that can change pack contents — \`@conduction/nextcloud-vue\` (the
\`rvo\`/\`open-gemeenten\`/\`den-haag\` packs) or \`@gouvfr/dsfr\` (the \`dsfr\` pack) — MUST be an
explicit, reviewed change whose diff of added/removed keys is listed in the changelog —
never a silent regenerate. Removing the legacy Amsterdam aliases at the end of the
deprecation window is a planned, pre-announced break that references the release that
announced it.
`

	fs.writeFileSync(iconsMdPath, content)
}

main().catch((err) => {
	console.error(err)
	process.exit(1)
})
