<?php

/**
 * Shipped token-set provenance: which sets the converter made, and what made the rest.
 *
 * SPDX-License-Identifier: EUPL-1.2
 * SPDX-FileCopyrightText: 2026 Conduction B.V.
 *
 * Three kinds of shipped set live side by side in `css/tokens/`: sets the
 * converter produced from an upstream theme (their header names
 * `TokenSetConverterService` and they carry a provenance block), sets built
 * from a brand file by `scripts/generate-brand-set.mjs`, and hand-authored
 * sets. The nightly sync only re-converts the first kind, so a converted set
 * whose provenance block is incomplete cannot be told apart from a hand edit,
 * and a brand-file set that lost its generator line looks hand-authored.
 * `summer-breeze` reads its own `--summer-*` vocabulary and gets no
 * `--nldesign-*` layer (decision 126, 9 Oct 2026).
 *
 * No Nextcloud runtime required: pure filesystem work over `css/tokens/`.
 *
 * @spec openspec/changes/nlds-theme-converter/specs/token-sets/spec.md#requirement-converted-sets-carry-provenance-and-are-reproducible-from-it
 */

declare(strict_types=1);

namespace OCA\Thematiq\Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Static provenance inventory over the shipped token sets.
 */
class TokenSetProvenanceTest extends TestCase {

	/**
	 * The header marker of a set the converter wrote.
	 */
	private const CONVERTER_MARKER = 'GENERATED by Thematiq TokenSetConverterService';

	/**
	 * The header marker of a set built from a brand file.
	 */
	private const BRAND_MARKER = 'GENERATED by scripts/generate-brand-set.mjs';

	/**
	 * The fields every converter provenance block names, with the shape of their value.
	 */
	private const PROVENANCE_FIELDS = [
		'input kind' => '/^[A-D] \(/',
		'source' => '/^\S+/',
		'converter' => '/^\d+\.\d+\.\d+$/',
		'mapping table' => '/^v\d+ sha256:[0-9a-f]{16}$/',
		'applied' => '/^\d+$/',
		'adapted' => '/^\d+$/',
		'kept' => '/^\d+$/',
		'skipped' => '/^\d+$/',
	];

	/**
	 * Repository root, derived from this test file's location.
	 */
	private function repoRoot(): string {
		return \dirname(__DIR__, 2);
	}//end repoRoot()

	/**
	 * The shipped light sets, keyed by id.
	 *
	 * @return array<string, string> Set id to file contents.
	 */
	private function shippedSets(): array {
		$sets = [];
		foreach (glob($this->repoRoot() . '/css/tokens/*.css') ?: [] as $file) {
			$sets[basename($file, '.css')] = (string)file_get_contents($file);
		}

		return $sets;
	}//end shippedSets()

	/**
	 * The first fifteen lines of a file: where a generator names itself.
	 *
	 * @param string $css The file contents.
	 */
	private function head(string $css): string {
		return implode("\n", \array_slice(explode("\n", $css), 0, 15));
	}//end head()

	/**
	 * The ids of the sets whose header names the converter.
	 *
	 * @return array<int, string>
	 */
	private function convertedSetIds(): array {
		$ids = [];
		foreach ($this->shippedSets() as $id => $css) {
			if (str_contains($this->head($css), self::CONVERTER_MARKER) === true) {
				$ids[] = $id;
			}
		}

		return $ids;
	}//end convertedSetIds()

	/**
	 * Every set the converter wrote names its input, source, converter
	 * version, mapping table hash and counts.
	 *
	 * @spec openspec/changes/nlds-theme-converter/specs/token-sets/spec.md#requirement-converted-sets-carry-provenance-and-are-reproducible-from-it
	 */
	public function testEveryConvertedSetCarriesACompleteProvenanceBlock(): void {
		$converted = $this->convertedSetIds();
		$this->assertGreaterThanOrEqual(
			38,
			\count($converted),
			'38 shipped sets were converter output when nlds-theme-converter was archived; fewer means a header was lost.'
		);

		$sets = $this->shippedSets();
		$offenders = [];
		foreach ($converted as $id) {
			foreach (self::PROVENANCE_FIELDS as $field => $shape) {
				$found = preg_match('/^\s*\*\s+' . preg_quote($field, '/') . ':\s+(.+?)\s*$/m', $sets[$id], $match);
				if ($found !== 1 || preg_match($shape, $match[1]) !== 1) {
					$offenders[] = $id . ': ' . $field;
				}
			}
		}

		$this->assertSame([], $offenders, "Converted sets with an incomplete provenance block:\n  - " . implode("\n  - ", $offenders));
	}//end testEveryConvertedSetCarriesACompleteProvenanceBlock()

	/**
	 * A set built from a brand file names its generator and carries no
	 * converter provenance, so the sync treats it as not its own.
	 *
	 * @spec openspec/changes/nlds-theme-converter/specs/token-sets/spec.md#requirement-converted-sets-carry-provenance-and-are-reproducible-from-it
	 */
	public function testBrandFileSetsNameTheirGeneratorNotTheConverter(): void {
		$this->assertFileExists($this->repoRoot() . '/scripts/generate-brand-set.mjs', 'The brand-file entry point must stay.');

		$brandSets = [];
		foreach ($this->shippedSets() as $id => $css) {
			if (str_contains($this->head($css), self::BRAND_MARKER) === false) {
				continue;
			}

			$brandSets[] = $id;
			$this->assertStringNotContainsString(self::CONVERTER_MARKER, $css, $id . ' is a brand-file set and must not claim to be converter output.');
			$this->assertDoesNotMatchRegularExpression('/^\s*\*\s+mapping table:/m', $css, $id . ' must carry no converter provenance block.');
		}

		foreach (['denhaag', 'example-gemeente'] as $known) {
			$this->assertContains($known, $brandSets, $known . ' is built from a brand file and must name scripts/generate-brand-set.mjs.');
		}
	}//end testBrandFileSetsNameTheirGeneratorNotTheConverter()

	/**
	 * Summer Breeze keeps its own vocabulary: no `--nldesign-*` layer, no
	 * converter provenance.
	 *
	 * @spec openspec/changes/nlds-theme-converter/specs/token-sets/spec.md#requirement-summer-breeze-keeps-its-own-vocabulary
	 */
	public function testSummerBreezeDeclaresNoNldesignLayer(): void {
		$css = ($this->shippedSets()['summer-breeze'] ?? null);
		$this->assertNotNull($css, 'css/tokens/summer-breeze.css must be shipped.');

		$code = (string)preg_replace('#/\*.*?\*/#s', '', $css);
		$this->assertDoesNotMatchRegularExpression('/--nldesign-[a-z0-9-]+\s*:/', $code, 'summer-breeze must declare no --nldesign-* property.');
		$this->assertMatchesRegularExpression('/--summer-color-primary\s*:/', $code, 'summer-breeze must declare its own primary.');
		$this->assertStringNotContainsString(self::CONVERTER_MARKER, $css, 'summer-breeze is not converter output.');
	}//end testSummerBreezeDeclaresNoNldesignLayer()
}//end class
